paritytech/cumulus

- .gitlab-ci.yml
- Cargo.lock
- collator/Cargo.toml
- collator/src/lib.rs
- consensus/Cargo.toml
- consensus/src/lib.rs
- runtime/Cargo.toml
- runtime/src/validate_block/implementation.rs
- test/client/Cargo.toml
- test/client/src/lib.rs
- test/runtime/Cargo.toml
- test/runtime/build.rs
(Just concentrate on the collator crate)
Open questions:
> Implement Collator

- consensus/src/lib.rs
head_data seems to be just the header of the parachain block but in this code it is deocded as an `Option<header>`.
Those data are coming from this associated type:
```rust
/// A stream that yields finalized head-data for a certain parachain.
type Finalized: Stream<Item = Vec<u8>> + Send;
```
I don't see why this should be an option.
> Fix inconsistent head_data

- Cargo.lock
- Cargo.toml
- README.md
- collator/Cargo.toml
- collator/src/lib.rs
- consensus/Cargo.toml
- consensus/src/import_queue.rs
- consensus/src/lib.rs
- runtime/src/lib.rs
- runtime/src/validate_block/implementation.rs
- runtime/src/validate_block/mod.rs
- runtime/src/validate_block/tests.rs
- test/parachain/Cargo.toml
- test/parachain/build.rs
- test/parachain/runtime/Cargo.toml
- test/parachain/runtime/build.rs
- test/parachain/runtime/src/lib.rs
- test/parachain/src/chain_spec.rs
- test/parachain/src/cli.rs
- test/parachain/src/main.rs
- test/parachain/src/service.rs
Adds a test parachain and all the code/fixes to get it running.
> Add test parachain

- README.md
This PR makes minor but helpful clarifications to the parachain registering instructions.
* Specifies the exact extrinsic to call
* Provides a value for the `ParaInfo` field
* Provides transaction parameters in actual parameter order
* Corrects the step number for exporting genesis state 3 -> 4
* Uses the full `--base-path` instead of the short `-d` to be
* more explicit
* consistent with previous commands
> Clarify instructions for registering a parachain.

- README.md
Updates the text of the parachain registration instruction to reference the correct step when the genesis state was generated.
> Minor fix to readme instructions

- test/parachain/src/command.rs
- test/parachain/tests/polkadot_argument_parsing.rs
Otherwise the first positional argument is just swallowed
Fixes #62
> Fix: relay chain arguments need a first argument "command"

- Cargo.lock
- Cargo.toml
- collator/Cargo.toml
- consensus/Cargo.toml
- message-broker/Cargo.toml
- message-broker/src/lib.rs
- network/Cargo.toml
- primitives/Cargo.toml
- primitives/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
This provides a new crate `cumulus-message-broker` for receiving downward messages and sending upward messages. The messages are currently just `()` and will be replaced in a later pr. This also only introduces the runtime side, providing the inherent data will come later as well.
> Introduce message broker for receiving and sending relay chain messages

- runtime/src/validate_block/implementation.rs
I was checking how proof would be checked with cumulus, and see that clear_prefix is not aligned with substrate, this PR fixes that.
(corresponding substrate code https://github.com/paritytech/substrate/blob/a2512e837003db3d3267764283edf31cf95a206c/primitives/state-machine/src/trie_backend_essence.rs#L239 ).
> Align trie iteration to substrate.

- test/parachain/Cargo.toml
- test/parachain/src/command.rs
> fix test collator compilation failure

- Cargo.lock
- parachain-upgrade/Cargo.toml
- parachain-upgrade/src/lib.rs
- primitives/Cargo.toml
- primitives/src/validation_function_params.rs
- runtime/src/validate_block/implementation.rs
- test/parachain/runtime/Cargo.toml
- test/parachain/runtime/src/lib.rs
This ensures that the crate compiles for `no_std`. Besides this, there
are some fixes to the crate code itself.
Fixes: https://github.com/paritytech/cumulus/issues/97
CC @akru
> Put `cumulus-parachain-upgrade` into the test parachain

- Cargo.lock
- collator/src/lib.rs
- network/Cargo.toml
- network/src/lib.rs
- network/src/tests.rs
- primitives/src/lib.rs
> Reject blocks without justification which don't have the best number

- test/parachain/src/command.rs
> Enable mdns polkadot

- test/parachain/src/command.rs
This PR adds the ability to specify a custom chainspec to the embedded relay chain node by passing `--chain some-spec.json`.
This is useful for testing the collator on local polkadot testnets.
> Allow custom Polkadot chainspec

- runtime/src/validate_block/implementation.rs
There is probably some bug in rustc which result in an invalid
compilation when using an `expect` at the given position. I'm still not
sure why this is happening, but this fix should fix it for now.
> Try to workaround the invalid compilation

- Cargo.lock
- collator/src/lib.rs
- network/src/lib.rs
- runtime/src/validate_block/tests.rs
- test/parachain/Cargo.toml
- test/parachain/build.rs
- test/parachain/runtime/build.rs
- test/parachain/src/chain_spec.rs
- test/parachain/src/integration_test.rs
- test/parachain/src/service.rs
- test/runtime/build.rs
Just print a warning when the internal block announcement validation of the `DelayedBlockAnnounceValidator` is not yet set. 
This also sets the block announcement validator for normal nodes.
> Fix block announcement validation

- Cargo.lock
- rococo-parachains/Cargo.toml
- rococo-parachains/contracts-runtime/Cargo.toml
- rococo-parachains/contracts-runtime/src/lib.rs
- rococo-parachains/pallets/contracts/Cargo.toml
- rococo-parachains/pallets/contracts/common/Cargo.toml
- rococo-parachains/pallets/contracts/rpc/Cargo.toml
- rococo-parachains/pallets/contracts/rpc/runtime-api/Cargo.toml
- rococo-parachains/pallets/contracts/rpc/runtime-api/src/lib.rs
- rococo-parachains/pallets/contracts/rpc/src/lib.rs
- rococo-parachains/pallets/contracts/src/lib.rs
- rococo-parachains/pallets/contracts/src/rent.rs
- rococo-parachains/src/command.rs
This reworks the default values used by the RelayChainCli for stuff like
the listen port etc.
This also renames all the contracts related stuff to `cumulus-*` to
support `.cargo/config` overrides.
> Rework default values used by the RelayChainCli

- runtime/src/validate_block/implementation.rs
This PR adds a new function to storage in order to check for change of the current block processing without querying the trie backend.
This way, this PR allows trie backend to fail on incomplete proofs.
> Fail when storage is not in proof

- .github/workflows/release-bot.yml
This should be using the most recent version of s3krit's github action otherwise it will fail.
> Bump release notes github action version

- rococo-parachains/src/cli.rs
- rococo-parachains/src/command.rs
Two commits:
1. Add a --raw flag to export-genesis-state
2. Switch `export-genesis-wasm` to output hex by default and also add `--raw` to get the previous functionality
This basically makes the behavior of `export-genesis-state` and `export-genesis-wasm` consistent and friendly when working with polkadot.js.api
That perhaps will break scripts and all, but we will have to do that anyway if we want them to be consistent and I think now is a good time.
> Make export-genesis-wasm output hex

- Cargo.lock
- Cargo.toml
- message-broker/Cargo.toml
- message-broker/src/lib.rs
- primitives/src/lib.rs
- rococo-parachains/runtime/Cargo.toml
- rococo-parachains/runtime/src/lib.rs
This is mostly a copy of the predating version with exception of some
renaming and alterations (e.g. the message handler takes an inbound
downward message by value, not by reference).
> Resurrect (a minimal version of) message-broker

- Cargo.lock
- message-broker/src/lib.rs
- network/src/lib.rs
- network/src/tests.rs
- parachain-upgrade/src/lib.rs
- rococo-parachains/contracts-runtime/src/lib.rs
- rococo-parachains/pallets/parachain-info/src/lib.rs
- rococo-parachains/runtime/src/lib.rs
- service/src/lib.rs
- test/runtime/src/lib.rs
This includes 
- renaming uses of `::Trait` to `::Config`
- renaming `trait Trait` declarations to `Config`
- fixing the fallout after https://github.com/paritytech/substrate/pull/7472 by introducing `BlockAnnounceError`, a box wrapper around a String.
- updating the 'static bound. This is needed for the further refactorings, namely moving the client into the `struct Collator`.
> Update polkadot to the latest master

- scripts/register_parachain.sh
- scripts/temp_parachain_types.json
Tested locally.
Usage: `{url} {wasm_file} {genesis_head} {para_id} {types_file}`
In practice: `scripts/register_parachain.sh ws://127.0.0.1:9944 "//Alice" ~/adder_genesis.wasm $(cat ~/adder_genesis.head) 100 scripts/temp_parachain_types.json`
I removed the balance setting thing as that's a separate concern and it didn't work for some reason.
> Update parachain registration script to new extrinsic

- Cargo.lock
- collator/src/lib.rs
- parachain-upgrade/Cargo.toml
- parachain-upgrade/src/lib.rs
- primitives/Cargo.toml
- primitives/src/lib.rs
- rococo-parachains/src/service.rs
- service/src/lib.rs
- test/client/Cargo.toml
- test/client/src/block_builder.rs
- test/service/src/lib.rs
This change plumbs the polkadot backend into the cumulus collator. This enables us to collate storage proofs from the relay-parent to the parachain. (Expected to come in following PRs)
Besides, the type of the inherent data payload was altered so as to incorporate the storage proof.
> Plumb polkadot backend into cumulus-collator

- Cargo.lock
- parachain-upgrade/src/lib.rs
- rococo-parachains/contracts-runtime/src/lib.rs
- rococo-parachains/runtime/src/lib.rs
- rococo-parachains/src/command.rs
- runtime/src/validate_block/implementation.rs
- test/runtime/src/lib.rs
- test/service/tests/integration.rs
- removed default chain_id, added SS58 prefix
- refactored logger params
> upgrade to latest polkadot

- rococo-parachains/src/chain_spec.rs
- rococo-parachains/src/command.rs
- test/service/src/chain_spec.rs
This PR changes the signature of the `try_get` function to not use a borrowed box. Clippy recommends this. Although cumulus does not use clippy, it still seems like a good change.
https://rust-lang.github.io/rust-clippy/master/index.html
> Remove borrowed box

- collator/Cargo.toml
- message-broker/Cargo.toml
- parachain-upgrade/Cargo.toml
- primitives/Cargo.toml
- rococo-parachains/Cargo.toml
- rococo-parachains/runtime/Cargo.toml
- test/runtime/Cargo.toml
- test/service/Cargo.toml
- xcm-handler/Cargo.toml
A minor PR to eliminate redundant spaces in Cargo.toml
NB: this also happens in the rococo-v1 branch. I am not clear about the workflow between rococo-v1 and master. If needed, I may also have a pr there.
> eliminate redundant spaces in Cargo.toml

- Cargo.lock
- collator/Cargo.toml
- network/Cargo.toml
Turns out this dependency is not used anywhere
> Remove polkadot-validation dependency

- runtime/src/validate_block/implementation.rs
Offchain indexing should be ignored when validation state.
This PR adds the function overload.
I could have call the externality, but seems more correct to noops.
> Ignore offchain indexing in validation function.

- Cargo.lock
- collator/src/lib.rs
- network/src/tests.rs
- parachain-upgrade/src/lib.rs
- primitives/src/lib.rs
- runtime/src/validate_block/implementation.rs
- runtime/src/validate_block/tests.rs
- test/client/src/block_builder.rs
- test/service/src/lib.rs
Depends on https://github.com/paritytech/polkadot/pull/2272
This PR doesn't update the Cargo.lock yet since it depends on the polkadot PR. FWIW, this PR passes `cargo check` with a proper Cargo.lock locally
> Replace ValidationData with PersistedValidationData

- Cargo.lock
- network/Cargo.toml
- network/src/lib.rs
- network/src/tests.rs
Instead of sending a `SignedFullStatement` this switches to a new struct
`BlockAnnounceData` that is being send alongside the block announcement.
The signed full statement contains the candidate commitments, meaning it
could be a full runtime upgrade that we send alongside a block
announcement... To prevent this, we now only send the candidate receipt
and the compact statement.
Requires: https://github.com/paritytech/polkadot/pull/2320
> Switch to custom `BlockAnnounceData`

- network/src/lib.rs
- network/src/tests.rs
The error variant is just for internal errors and we need to return
`Failure` always when the other node send us an invalid statement.
> Block announce validation should use the correct `Validation` result

- xcm-handler/src/lib.rs
**Question**
Are HRMP messages should be tagged as routed from the relay chain for the XCM executor, didn't they?
> Fix HRMP message source location 

- rococo-parachains/runtime/src/lib.rs
This makes XCM handler accessible from extrinsics
> Add call to XCM Handler

- Cargo.lock
- collator/src/lib.rs
- parachain-system/src/lib.rs
- parachain-system/src/relay_state_snapshot.rs
- rococo-parachains/src/service.rs
- runtime/src/validate_block/implementation.rs
- runtime/src/validate_block/tests.rs
- test/client/src/block_builder.rs
- test/relay-sproof-builder/src/lib.rs
- test/service/src/lib.rs
> Migrate from MQCs in persisted validation data to merkle proofs

- xcm-handler/src/lib.rs
According to my understanding of the XCM spec, location of parachains is of the form:
`MultiLocation::X2(Junction::Parent, Junction::Parachain { id })`
This fix was necessary to execute the following message and forward the effects to via HRMP:
```rust
Xcm::WithdrawAsset {
assets: vec![MultiAsset::ConcreteFungible {
id: location,
amount: amount.into(),
}],
effects: vec![Order::DepositReserveAsset {
assets: vec![MultiAsset::All],
dest: MultiLocation::X2(Junction::Parent, Junction::Parachain { id: para_id.into() }),
effects: vec![Order::DepositAsset {
assets: vec![MultiAsset::All],
dest: MultiLocation::X1(Junction::AccountId32 {
network: network.clone(),
id: T::AccountId32Converter::convert(recipient.clone()),
}),
}],
}],
}
```
> Use correct relative path for parachain

- Cargo.lock
- Cargo.toml
- client/collator/Cargo.toml
- client/collator/src/lib.rs
- pallets/parachain-system/Cargo.toml
- pallets/parachain-system/src/lib.rs
- primitives/core/Cargo.toml
- primitives/core/src/lib.rs
- primitives/parachain-inherent/Cargo.toml
- primitives/parachain-inherent/src/client_side.rs
- primitives/parachain-inherent/src/lib.rs
- test/client/Cargo.toml
- test/client/src/block_builder.rs
This renames and moves the `SystemInherentData` into its own crate.
The struct is now called `ParachainInherentData`. Besides moving the
struct, this also moves the code for creating this struct into this crate.
> Move parachain inherent data into its own crate

- pallets/xcm-handler/src/lib.rs
Changed `XcmError::Undefined` to `XcmError::CannotReachDestination`, on upward and horizontal message send failure.
> Use `XcmError::CannotReachDestination` on message send failure in `SendXcm` implementation

- Cargo.lock
- pallets/xcm-handler/Cargo.toml
- pallets/xcm-handler/src/lib.rs
- rococo-parachains/runtime/src/lib.rs
With xcm local execution support, modules like `xtokens` don't have to do workarounds and use xcm-executor to do the execution anymore.
As discussed with @shawntabrizi and @xlc, updating xcm-handler's `SendXcm` implementation can't achieve the same goal, unless adding a `origin` parameter to the `send_xcm` signature, which is not necessary IMO as in other cases this param is not needed:
```rust
fn send_xcm(origin: MultiLocation, dest: MultiLocation, msg: Xcm) -> Result<(), XcmError> {}
```
> Support xcm local execution in xcm-handler.

- Cargo.lock
- client/collator/src/lib.rs
- client/consensus/common/Cargo.toml
- client/consensus/common/src/lib.rs
- client/network/Cargo.toml
- client/network/src/lib.rs
- client/network/tests/sync.rs
- client/service/src/lib.rs
- rococo-parachains/src/service.rs
- test/service/Cargo.toml
- test/service/src/lib.rs
- test/service/tests/integration.rs
There was an issue that non collator, actually all nodes that didn't produced a particular block, did not propagate this block to its peers. This pr fixes this by propagating every imported block that was not build by the local block to its peers. Actually this is a hack, until it is fixed in Substrate ;)
Fixes: https://github.com/paritytech/cumulus/issues/335
To make the tests work, the following pr in Substrate is required: https://github.com/paritytech/substrate/pull/8325
(I have executed the tests locally with the mentioned pr and everything is green)
> Fix block propagation between non-collator nodes

- pallets/xcm-handler/src/lib.rs
This adds back the correct HRMP path for parachain siblings. The changes here already existed in the `rococo-v1` branch (via #322), but somehow they were undone. I suspect due to a merge from master, which did not contain the changes.
cc @shaunxw
> Use correct HRMP path for parachain siblings

- pallets/parachain-system/src/lib.rs
The first change in this PR is to the underlying storage structure of how Validation Function Upgrades are handled.
Before, we had a single storage item which has both the block when the upgrade would happen, and the whole wasm we would upgrade with. We would then check every block if it was the right block to upgrade on, reading the whole wasm each time!
Here we split storage into two storage items, one where we can more quickly check the block number being correct, and the other where only after we confirm we need the new validation function, we get it.
----
The second change allows Root to set the specific block where they expect the relay chain to upgrade their wasm.
This is useful if you want to coordinate with the relay chain for some different upgrade schedule than would be set up …
> Improve Storage and Add `set_upgrade_block` to Validation Function Upgrade

- client/network/src/lib.rs
- client/network/src/tests.rs
If we receive a block announcement without a statement attached that
matches the latest backed block, it is valid and we need to approve the
block announcement to download the block.
> Approve block announcements of backed blocks

- client/collator/src/lib.rs
- client/network/src/lib.rs
- client/network/src/tests.rs
Internally we get notified on the channel for our candidate anyway.
Besides that polkadot will compress the pov which leads to a different
pov hash and thus, would lead to a failing check on the `pov_hash`.
> Remove pov hash comparison when waiting on a block to announce

- pallets/parachain-system/src/lib.rs
This PR makes the dispatchable `set_validation_data` function public in the parachain system pallet. This allows calling the function during tests as we're trying to do in https://github.com/PureStake/moonbeam/pull/339
This is precedented in the timestamp pallet as well https://github.com/paritytech/substrate/blob/565078a965698c425cd909db55abb3b381e27701/frame/timestamp/src/lib.rs#L192
cc @4meta5
> Make `set_validation_data` public

- pallets/parachain-system/src/lib.rs
Authorize an upgrade via XCM/DMP and then actually pass in the code via a normal transaction.
> Two-stage upgrade for parachains

- pallets/parachain-system/src/lib.rs
Instead of `ensure` with dedicated errors use `panic` or `assert`. See
for details #410
Closes #410
> Panic instead of ensure

- Cargo.lock
- polkadot-parachains/rococo-runtime/src/lib.rs
- polkadot-parachains/shell-runtime/src/lib.rs
- test/runtime/src/lib.rs
This PR integrates the modern mechanism for reporting runtime version, introduced in https://github.com/paritytech/substrate/pull/8688.
This will do no difference until https://github.com/paritytech/polkadot/pull/3045 is merged.
> Slap runtime_version macro everywhere

- polkadot-parachains/statemine-runtime/src/lib.rs
Given a balance deposit (with account creation) was possible by paying only 3_000_000 weight, the old value is probably not conservative enough. Now that's gone up by a factor of 1000, it should be ok.
> Bump XCM weight to something more conservative

- client/consensus/common/src/parachain_consensus.rs
It doesn't make sense to log them as a warning, especially when it could
happen that a parachain id could be reused over the lifetime of a relay
chain.
> Decrease log levels

- .github/workflows/srtool.yml
This PR adds a new github workflow to the CI.
It does the following:
- run `srtool`
- save the wasm
- install/run `subwasm`
- fetch the info, including the blake2_256 hash from the wasm
- store relevant artifacts
> Add srtool + subwasm workflow

- client/collator/src/lib.rs
- pallets/parachain-system/src/lib.rs
- polkadot-parachains/rococo-runtime/src/lib.rs
- polkadot-parachains/shell-runtime/src/lib.rs
- polkadot-parachains/src/chain_spec.rs
- polkadot-parachains/statemine-runtime/src/lib.rs
- polkadot-parachains/statemint-runtime/src/lib.rs
- polkadot-parachains/westmint-runtime/src/lib.rs
- test/runtime/src/lib.rs
- test/service/src/chain_spec.rs
This is basically a hack that prevents the inclusion of `:code` in the
storage proof. A proper fix requires some changes to the trie crate to
not include nodes that aren't read.
> Do not include `:code` in the storage proof if not required

- .github/workflows/srtool.yml
- switch to a tag (v0.1.0) for the `chevdor/srtool-actions` (previously using a `draft` branch)
- trigger to only tags & ignore folders not involved in the runtime
- add weekly build schedule (every Monday @ 2am)
- add timestamp to the artifacts
> feat(ci): update runtime build workflow

- Cargo.lock
- pallets/parachain-system/src/tests.rs
- polkadot-parachains/src/chain_spec.rs
- polkadot-parachains/tests/purge_chain_works.rs
- test/service/src/chain_spec.rs
- test/service/src/lib.rs
This PR probably miss some changes. I will finish before end of the day.
The related substrate breaking change is https://github.com/paritytech/substrate/pull/8990
> update substrate/polkadot with construct_runtime changes

- Cargo.lock
- Cargo.toml
- client/collator/Cargo.toml
- client/collator/src/lib.rs
- pallets/parachain-system/Cargo.toml
- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/validate_block/implementation.rs
- pallets/parachain-system/src/validate_block/tests.rs
- polkadot-parachains/Cargo.toml
- polkadot-parachains/rococo-runtime/Cargo.toml
- polkadot-parachains/rococo-runtime/src/lib.rs
- polkadot-parachains/shell-runtime/src/lib.rs
- polkadot-parachains/statemine-runtime/Cargo.toml
- polkadot-parachains/statemine-runtime/src/lib.rs
- polkadot-parachains/statemint-runtime/Cargo.toml
- polkadot-parachains/statemint-runtime/src/lib.rs
- polkadot-parachains/westmint-runtime/Cargo.toml
- polkadot-parachains/westmint-runtime/src/lib.rs
- primitives/core/src/lib.rs
- primitives/timestamp/Cargo.toml
- primitives/timestamp/src/lib.rs
- test/client/Cargo.toml
- test/client/src/block_builder.rs
- test/client/src/lib.rs
- test/runtime-upgrade/Cargo.toml
- test/runtime/Cargo.toml
- test/runtime/src/lib.rs
- test/service/Cargo.toml
This adds support for checking the timestamp inherent while validating a
block. This will use the relay chain slot number * relay chain slot
duration to calculate a timestamp. This timestamp is used to check the
timestamp in the timestamp inherent.
Fixes: https://github.com/paritytech/cumulus/issues/422
> Adds support for checking the timestamp inherent while validating a block

- Cargo.lock
- pallets/session-benchmarking/Cargo.toml
- polkadot-parachains/statemine-runtime/Cargo.toml
- polkadot-parachains/statemine-runtime/src/lib.rs
- polkadot-parachains/statemint-runtime/Cargo.toml
- polkadot-parachains/statemint-runtime/src/lib.rs
- polkadot-parachains/westmint-runtime/Cargo.toml
- polkadot-parachains/westmint-runtime/src/lib.rs
This is required to support patching Substrate, as otherwise there are
two crates with the same name.
> Rename `pallet-session-benchmarking` crate

- pallets/parachain-system/src/validate_block/implementation.rs
Calls drop to ensure memory of the compacted proof is dropped.
> Explicit drop of compact proof memory.

- polkadot-parachains/rococo-runtime/src/lib.rs
- polkadot-parachains/shell-runtime/src/lib.rs
- test/runtime/src/lib.rs
Parachain runtimes in this repo were using 2 seconds instead of 1/2 a second.
> Fix Max Block Weight

- pallets/collator-selection/src/lib.rs
- pallets/collator-selection/src/mock.rs
- pallets/collator-selection/src/tests.rs
- polkadot-parachains/statemine-runtime/src/lib.rs
- polkadot-parachains/statemint-common/src/impls.rs
- polkadot-parachains/statemint-runtime/src/lib.rs
- polkadot-parachains/westmint-runtime/src/lib.rs
This PR checks to make sure that there is a min amount of collators before a collator gets kicked, or tries to leave. This is a defence mechanism for better disaster recovery of a chain
> min collator check

- pallets/parachain-system/src/lib.rs
> add RelaychainBlockNumberProvider

- Cargo.lock
- polkadot-parachains/statemine/Cargo.toml
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/Cargo.toml
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/Cargo.toml
- polkadot-parachains/westmint/src/lib.rs
- test/runtime/src/lib.rs
- test/service/Cargo.toml
- test/service/src/lib.rs
- test/service/tests/runtime_upgrade.rs
This brings back the runtime upgrade test and also updates Substrate &
Polkadot.
Fixes: https://github.com/paritytech/cumulus/issues/524
> Bring back runtime upgrade test

- .github/workflows/srtool.yml
This PR brings:
- add builds for "statemint", "rococo", "shell"
- switch to `chevdor/srtool-actions@v0.3.0` which default the new srtool image from `paritytech/srtool`
- bumps up the version of `subwasm`
- cleanup
- ability to start builds on-demand
> upgrade srtool-actions and subwasm

- pallets/parachain-system/src/tests.rs
- pallets/xcmp-queue/src/mock.rs
- polkadot-parachains/rococo/src/lib.rs
- polkadot-parachains/shell/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
- test/runtime/src/lib.rs
This ensures that `parachain-system` has all the proper configuration settings in the `construct_runtime` across all runtimes.
> Make `parachain-system` config consistent

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
We need to upgrade both runtimes because of compact proofs.
> bump spec version of statemine and westmint

- client/consensus/common/src/parachain_consensus.rs
- client/consensus/common/src/tests.rs
Closes: https://github.com/paritytech/cumulus/issues/534
> Do not set best block when there already exists a best block with an higher number

- .gitlab-ci.yml
- scripts/ci/pre_cache.sh
`build --release --bin polkadot-collator` takes 5 minutes after a test, `test --release --all` gets built in ~8 minutes without the cache.
So in the case of building after the test it saves a parallel/concurrent task, but certainly it doesn't make sense to run it every time on PRs, not even on every master pipeline.
I can run the build as it is, in the same job, but only when the pipeline's executed by schedule/trigger, @lovelaced WDYT?
Closes: https://github.com/paritytech/ci_cd/issues/141
> CI: build a test artifact

- .github/workflows/srtool.yml
Upgrade `subwasm` from 0.12.0 to 0.13.2 to prevent erroneous values regarding to reported size and hashes for the compressed runtime.
> ci: upgrade subwasm

- .github/workflows/release-bot.yml
Previous we used to send matrix notification for any edit, that ends up spamming the notification channel.
This PR only sends a notification on actuall release.
The message is also split on multiple line to make it more readable and easier to edit.
> ci: reduce the list of events triggering matrix messages

- pallets/xcmp-queue/src/lib.rs
- primitives/core/src/lib.rs
https://github.com/paritytech/polkadot/pull/3538
> Polkadot companion (XCM-simulator)

- .github/workflows/docs.yml
This PR adds a CI job that builds and published the rustdocs to github pages. Similar to crates.parity.io, https://paritytech.github.io/frontier/rustdocs/pallet_evm/, or https://purestake.github.io/moonbeam/moonbeam_runtime/index.html
This is useful when working on downstream code to have an API guide quickly available, especially since github will host it for free.
This will need a little bit of help from someone with some permissions on this repo to setup the publishing source as the `gh-pages` branch. [docs](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)
> Publish rustdocs to github pages

- .github/workflows/docs.yml
the `cargo doc` job takes 55 minutes! I'll rewrite it to gitlab CI. Just merge this fix for now.
Docs are published at https://paritytech.github.io/cumulus.
> CI: fix gh doc publishing

- Cargo.lock
- pallets/dmp-queue/src/lib.rs
- pallets/xcm/src/lib.rs
- pallets/xcmp-queue/src/lib.rs
- pallets/xcmp-queue/src/mock.rs
- polkadot-parachains/pallets/ping/src/lib.rs
- polkadot-parachains/rococo/src/lib.rs
- polkadot-parachains/shell/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
- primitives/utility/src/lib.rs
- test/service/src/lib.rs
Companion for paritytech/polkadot#3404.
> Use new MultiLocation syntax everywhere

- polkadot-parachains/res/statemine.json
- polkadot-parachains/res/statemine_genesis.json
- polkadot-parachains/res/statemint.json
- polkadot-parachains/res/tick.json
- polkadot-parachains/res/track.json
- polkadot-parachains/res/trick.json
- polkadot-parachains/res/westmint.json
- polkadot-parachains/res/westmint_genesis.json
necessary because of https://github.com/paritytech/substrate/pull/9491
> Remove `lightSyncState` Field from Chain Specs

- Cargo.lock
- client/collator/src/lib.rs
- pallets/aura-ext/src/lib.rs
- pallets/collator-selection/src/mock.rs
- pallets/xcmp-queue/src/mock.rs
- polkadot-parachains/rococo/src/lib.rs
- polkadot-parachains/shell/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
The XCM stuff in particular needs a look over
> bump deps, fix aura-ext pallet, and fill in stubs for XCM

- .github/workflows/srtool.yml
This bumps subwasm to the latest version in order to be able to decode V14 runtimes.
That will resolve the CI issues we can see [here](https://github.com/paritytech/cumulus/actions/workflows/srtool.yml).
> chore: bump subwasm version to support V14 runtimes

- .github/workflows/extrinsic-ordering-check-from-bin.yml
- scripts/extrinsic-ordering-filter.sh
This PR adds running a manual check for the extrinsic ordering.
A test run can be seen here: https://github.com/chevdor/cumulus/actions/runs/1287438927
What currently fails for some reason atm is not critical, the CI seems to fail killing the `polkadot-collator` (it works fine with `polkadot`).
> Add extrincic ordering check to CI

- polkadot-parachains/westmint/src/lib.rs
We often get requests for WND as the faucet doesn't provide enough for asset creation. Just lower the Westmint deposit on assets so people can test easily.
> Make asset creation on westmint low cost

- client/network/src/lib.rs
- client/network/src/tests.rs
This is required to make it more future proof when contextual execution is coming. While this
changes the `BlockAnnounceData` type, it is written in a way to make it backwards compatible.
> Add `relay_parent` to block announce data

- scripts/changelog/.gitignore
- scripts/changelog/README.md
- scripts/changelog/changelog.sh
While the generation of the changelogs will be improved, this is a script that helps already today.
This script is **not** by any CI or automation atm and is ran only manually.
> Add script to generate simple changelogs

- .github/workflows/srtool.yml
This PR bumps the `subwasm` version used in CI.
> Bump subwasm version

- Cargo.lock
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemine/src/weights/pallet_utility.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/statemint/src/weights/pallet_utility.rs
- polkadot-parachains/westmint/src/lib.rs
- polkadot-parachains/westmint/src/weights/pallet_utility.rs
companion for https://github.com/paritytech/substrate/pull/9934
polkadot companion: paritytech/polkadot#4075
> Companion for `dispatch_as`

- polkadot-parachains/rococo/src/lib.rs
- polkadot-parachains/shell/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
1 million quite likely is not a safe default weight for XCMs given the values seen in Westend benchmarks.
This also adjusts Westmint's weights to 1B to make it more straightforward to spot weight issues in testing.
Also adjusts shell and rococo parachain.
closes #734
> Adjust XCM weights to 1B

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
We would like the Call indices to be the same between the different Statemint flavors.
This PR adjusts Westmint to be in line with Statemint and Statemine (except for adding `pallet-sudo` as index 255).
merge after #726 
closes #729
> Align Call Indices between Westmint and Statemint

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
Bump the `spec_version` for Statemint, Statemine and Westmint.
> Bump Statemint Spec Version to 600

- client/cli/src/lib.rs
- parachain-template/node/src/chain_spec.rs
- parachain-template/node/src/cli.rs
- parachain-template/node/src/command.rs
- polkadot-parachains/src/chain_spec.rs
- polkadot-parachains/src/command.rs
This was never planned to be a permanent feature. This was mainly added for testing purposes, but
now was copied by everybody. The users should be more specific about the para id and set this
properly in the chain spec.
> Remove `parachain-id` cli command

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
...so they are more similar in structure.
Should not induce any logic changes.
> Align the Statemint Runtimes 

- parachain-template/runtime/src/lib.rs
- polkadot-parachains/rococo/src/lib.rs
- polkadot-parachains/shell/src/lib.rs
This PR bumps the spec versions to match the scheme we adopted on statemint and statemine.
> Bump spec versions

- README.md
- docker/polkadot-collator_builder.Containerfile
- docker/test-parachain-collator.dockerfile
- add `polkadot-collator_builder.Containerfile` to simplify/unify the build process for the users and docs on how to use it
- not quite sure if you use `docker/test-parachain-collator.dockerfile` but I've optimized it a bit.
> polkadot collator builder

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
https://github.com/paritytech/cumulus/pull/517 changed the calls of the  `parachain_system` pallet.
--> Bump transaction version.
> bump transaction_version due to parachain_system change

- Cargo.lock
- polkadot-parachains/Cargo.toml
- polkadot-parachains/rococo/Cargo.toml
Fixes: #750 
The problem was there are two different packages with the same name: `rococo-runtime` and it was generating some conflict when compiling since they have different versions too.
Not sure why it is only complaining when using `--features runtime-benchmarks`
> Fix package naming conflict

- .rustfmt.toml
- Cargo.lock
- parachain-template/node/Cargo.toml
This PR is mainly to fix the error `[E0670]: async fn is not permitted in the 2015 edition` when
using Vim along with rust-analyzer, also removes an unused dependency from parachain-template.
Ref: https://github.com/rust-analyzer/rust-analyzer/issues/1959
Can be also merged into #759 if you prefer.
> Specify edition 2021 in .rustfmt.yml

- .github/workflows/draft_release.yml
This PR fixes the release generation in CI.
It specifies the branch to checkout and provides a more appropriate default.
The full fix requires also to backport the following to the `release-statemine-v6`:
- #761
- this PR
> Fix CI for runtimes and rococo

- .github/workflows/srtool.yml
Until now, the [Srtool Workflow](https://github.com/paritytech/cumulus/actions/workflows/srtool.yml) was started only manually. 
This PR additionnally triggers the build to ensure the runtimes keep building when new changes are pushed to the following branches:
- master
- release branches
> Add srtool check in master and release branches

- pallets/xcmp-queue/src/lib.rs
Companion to https://github.com/paritytech/polkadot/pull/4358
> Fix use of weight limit errors

- pallets/xcmp-queue/src/lib.rs
Backport the XCMP queue fix (https://github.com/paritytech/cumulus/pull/791) to 0.9.12
> Backport Fix use of weight limit errors (#791)

- pallets/xcmp-queue/src/lib.rs
Backport the xcmp queue fix from #791 for the Polkadot 0.9.13 version of Cumulus.
> Backport Fix use of weight limit errors (#791) for Polkadot 0.9.13

- .github/workflows/release-01_rc-automation.yml
A quick workaround that allows started the RC workflow when it fails to start as it should.
> Allow manual start

- polkadot-parachains/src/chain_spec.rs
> Increase statemine balance

- pallets/xcmp-queue/src/lib.rs
Because seeing `.1` and `.2` irks me to no end.
Mostly renames, but also contains some helper methods to construct a new type using the builder pattern.
> Refactor some types in XCMP queue

- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/validate_block/implementation.rs
- pallets/parachain-system/src/validate_block/tests.rs
- test/client/src/lib.rs
- test/runtime/src/lib.rs
- test/runtime/src/test_pallet.rs
- test/service/benches/transaction_throughput.rs
- test/service/src/chain_spec.rs
This adds support for returning a custom header from `validate_block`. Before this, we always
returned the header of the block that was validated (and still do it by default). However, after
this pr it is possible to set a custom header or better custom head data that will be returned
instead from `validate_block`. This can be for example when a chain wants to fork.
> Adds support for returning a custom header from `validate_block`

- pallets/xcmp-queue/src/lib.rs
- pallets/xcmp-queue/src/migration.rs
- pallets/xcmp-queue/src/mock.rs
- pallets/xcmp-queue/src/tests.rs
- parachain-template/runtime/src/lib.rs
- polkadot-parachains/rococo-parachain/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
Implementation follows closely to the UMP overweight message handling, as seen [here in this PR](https://github.com/paritytech/polkadot/pull/3575).
Fixes paritytech/srlabs_findings#145.
> Support overweight messages in XCMP queue

- Cargo.lock
- parachain-template/runtime/src/lib.rs
- polkadot-parachains/rococo-parachain/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
- test/client/src/lib.rs
- test/runtime/src/lib.rs
- test/service/src/lib.rs
Adding the `CheckNonZeroSender` signed extension a la paritytech/substrate#10413.
Fixes #840.
> Add CheckNonZeroSender to runtime configs

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
> Disable asset transfers on Statemint (against Statemint release branch v6.0.1)

- test/service/src/chain_spec.rs
Adds support for changing the para id relative easily. While this is currently not needed, we may
need it at some later point.
> Test-runtime: Support changing the `ParaId`.

- polkadot-parachains/rococo-parachain/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
Ensure that any assets under the Assets pallet is prefixed by a `PalletInstance(assets_pallet_index)` junction.
> Update XCM MultiLocation prefixes for assets

- Cargo.lock
- client/relay-chain-local/src/lib.rs
- primitives/core/src/lib.rs
https://github.com/paritytech/polkadot/pull/4545
> companion for polkadot#4545 (session-info v2)

- Cargo.lock
- pallets/parachain-system/proc-macro/Cargo.toml
Think maybe we should get dependabot working on this repo so that we don't have to manually update crates.
> Update proc-macro2 to 1.0.36

- client/collator/src/lib.rs
- pallets/parachain-system/src/lib.rs
- parachain-template/runtime/src/lib.rs
- polkadot-parachains/rococo-parachain/src/lib.rs
- polkadot-parachains/seedling/src/lib.rs
- polkadot-parachains/shell/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
- primitives/core/src/lib.rs
- test/runtime/src/lib.rs
- test/service/tests/full_node_catching_up.rs
- test/service/tests/migrate_solo_to_para.rs
https://github.com/paritytech/cumulus/pull/825 brought support for returning a custom header as part of the validation phase. This was tested only in isolation, aka not in a integration test. While testing it, we found out that we missed to also handle the client side correctly when there is a custom header to be returned. To be more precise, we need to return the new custom header also as part of the collation because otherwise the validation fails on the relay chain. This pr fixes this by adding an integration test and then it follows on what was outlined in https://github.com/paritytech/cumulus/pull/881
Fixes: https://github.com/paritytech/cumulus/issues/881
> Fix solo to para custom header return

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
Merging back changes from last statemine/mint release ( #902 ).
This merges https://github.com/paritytech/cumulus/pull/748 back to master.
> bump transaction_version due to parachain_system change (#748)

- pallets/xcmp-queue/src/lib.rs
- pallets/xcmp-queue/src/tests.rs
With #701 we tried to fix some infinite loop related to encoded blobs, however that lead actually to
not being able to process encoded blobs at all. The reason for this is that `decode_all` doesn't
consume the given input. The point of this function is that it returns an error if the data couldn't
be decoded or there is still data left. However, this means that the check
`remaining_fragments.len() < last_remaining_fragments.len()` would always fail.
We remove the while loop, because we decode the entire fragment anyway or it fails. Aka, we don't
need to loop here. Next we remove the broken check and we directly reset the
`remaining_fragments` (because `decode_all` doesn't consume anything).
> xcmp-queue: Fix handling of encoded blobs

- Cargo.lock
- polkadot-parachains/statemine/src/lib.rs
See: https://github.com/paritytech/substrate/pull/10650#discussion_r786932021
fixes https://github.com/paritytech/cumulus/issues/910
> Add the uniques migration for statemine

- parachain-template/runtime/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
https://github.com/paritytech/substrate/pull/10592 made it possible to reduce the combination of `add_benchmark`+`list_benchmark` to just one `define_benchmarks`.  
This MR refactors the code to use it.
Same as in Polkadot https://github.com/paritytech/polkadot/pull/4760  
- The change can be verified by listing all benchmarks: `cargo run --features=runtime-benchmarks --bin polkadot-collator -- benchmark --chain=westmint-dev --pallet="*" --extrinsic="*" --list` for `westmint`, `statemint` and `statemine`.
> Use `define_benchmarks!`

- client/pov-recovery/src/lib.rs
- client/pov-recovery/tests/pov_recovery.rs
- client/service/src/lib.rs
- parachain-template/node/src/service.rs
- polkadot-parachains/src/service.rs
- test/service/Cargo.toml
- test/service/src/lib.rs
Pov recovery was before only enabled for collators. The reason behind this was prevention of spam of
the relay chain for block recovery. However, recent events has shown that this wasn't a good idea.
So, this pr enables pov-recover for normal full nodes as well, but with a much higher delay before
trying to recover a block. This means that full nodes will wait in minimum 2.5 minutes and in
maximum 5 minutes before recovering a block. This should give collators in "normal mode" enough time
to recover a block (they wait in maximum 6 seconds after they have seen a new candidate in the relay
chain) before recovering a block. So, we should hopefully not spam the relay chain.
> pov-recovery: Enable pov-recovery as well on full nodes

- polkadot-parachains/parachains-common/src/impls.rs
https://github.com/paritytech/substrate/blob/master/frame/support/src/traits/tokens/currency.rs#L158
https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L1647
Since 0.9.12 of substrate, there is no need for a separate of balances event in runtime.
> fix: remove duplicate event of pallet_balances

- Cargo.lock
- client/cli/Cargo.toml
- client/cli/src/lib.rs
- pallets/parachain-system/src/validate_block/implementation.rs
- pallets/xcmp-queue/src/mock.rs
- parachain-template/node/Cargo.toml
- parachain-template/node/src/cli.rs
- parachain-template/runtime/src/lib.rs
- polkadot-parachains/Cargo.toml
- polkadot-parachains/rococo-parachain/src/lib.rs
- polkadot-parachains/shell/src/lib.rs
- polkadot-parachains/src/cli.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
- test/runtime/src/lib.rs
- test/service/src/genesis.rs
It turns out that all the commits in the `polkadot-v0.9.16` branch are needed. This PR adds them in to the parachains release branch also.
Fixes: https://github.com/paritytech/cumulus/issues/938
This also makes sure we are using exactly the same substrate / polkadot version as Basti's release branch.
> merge from cumulus release branch inc extra commit

- README.md
- polkadot-parachains/src/cli.rs
A follow-up for https://github.com/paritytech/cumulus/pull/739
Copy-pasting commands from README won't work since the id flag got removed.
Also dropped it from `export-genesis-state` since it's unused
> Fix `--parachain-id` usage in README guide

- .github/workflows/release-02_create-draft.yml
This fixes scripts/changelog/bin/changelog being unable to find the srtool digest for rococo-parachain.
[Current example of CI breakage](https://github.com/paritytech/cumulus/runs/5020707952?check_suite_focus=true), see step "Generate release notes"
> ci: fix broken reference to rococo srtool digest

- .github/workflows/release-02_create-draft.yml
This is https://github.com/paritytech/cumulus/pull/943, backported to **release-parachains-v7.0.0**
> ci: fix broken reference to rococo srtool digest (backport of #943)

- .github/workflows/release-02_create-draft.yml
rust outputs these with underscores, so `rococo-parachain` ends up as `rococo_parachain`, this breaks assumptions in the ci publish-runtimes step of release-02_create-draft, so we move it back to where it's expected
> ci: fix publish-runtimes for parachains containing - in name

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
`RemoveCollectiveFlip` was already run in the previous release: 
- https://github.com/paritytech/cumulus/blob/release-statemine-v6.0.1/polkadot-parachains/statemine/src/lib.rs#L783-L794
- https://github.com/paritytech/cumulus/blob/release-statemine-v6.0.1/polkadot-parachains/westmint/src/lib.rs#L770-L781
`UniquesV1Migration` is missing for Westmint:
- https://github.com/paritytech/cumulus/blob/release-parachains-v7.0.0/polkadot-parachains/westmint/src/lib.rs#L772
> Add / Remove migrations

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
There are some changes to the transaction structures in this statemine/statemint release so it requires a new transaction version.
> Bump transaction version for release 700

- .github/workflows/release-10_docker.yml
Current docker ci is broken due to bash issues when release notes contain special characters, this change quotes those strings to fix that issue.
See also https://github.com/paritytech/cumulus/runs/5140919334
> ci: fix bash quoting in docker ci

- Cargo.lock
- polkadot-parachains/Cargo.toml
Merging back v7 changes: bump collator version
(part of https://github.com/paritytech/cumulus/issues/969 )
> Bump collator version

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
Bump statemint/statemine transaction version as a breaking change was released.
(part of https://github.com/paritytech/cumulus/issues/969 )
> bump tx version (#966)

- .gitlab-ci.yml
- parachain-template/node/Cargo.toml
This allows:
```
cargo build -p parachain-template-node --features runtime-benchmarks
```
To succeed.
> Fix Runtime Benchmarks Feature Flag in Parachain Template

- parachain-template/runtime/Cargo.toml
sync solution from #887
Command cargo build -p parachain-template-runtime was broken.
> Fix parachain-template-runtime build fail

- polkadot-parachains/canvas-kusama/src/lib.rs
- polkadot-parachains/canvas-kusama/src/xcm_config.rs
This recently happened for the other runtimes. This applies a similar refactor to the Canvas runtime. This also re-enables the relay chain as root that was disabled by accident.
> Move Canvas xcm config to its own module

- parachain-template/node/src/command.rs
- polkadot-parachains/src/command.rs
Before this fix the relay chain node name was always a random generated, because we did not had
implemented all the required methods of the `CliConfiguration` trait.
Closes: https://github.com/paritytech/cumulus/issues/556
> Fix relay chain node name

- polkadot-parachains/canvas-kusama/src/lib.rs
We can use the new `state_version` as we intent to reset the rococo para chain with the next upgrade anyways. `spec_version` is bumped because it wasn't since the last runtime upgrade.
> Canvas: Bump `spec_version` and `state_version`

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
Remove migrations that have been executed on statemine and westmint
(part of https://github.com/paritytech/cumulus/issues/969 )
> Remove migrations that have been executed

- scripts/benchmarks.sh
we should be using production profile for benchmarks.
`--raw` does not exist: https://github.com/paritytech/substrate/pull/10771
> updating benchmarking script

- polkadot-parachains/canvas-kusama/src/contracts.rs
- polkadot-parachains/canvas-kusama/src/lib.rs
We expect some storage changes during the existence on rococo. Run the storage migrations defined in `pallet-contracts` in order to allow runtime upgrades without resetting the chain.
> canvas: Run migrations defined by `pallet-contracts`

- client/cli/src/lib.rs
The new cli  option `--runtime-cache-size` introduced in https://github.com/paritytech/substrate/pull/10177 does not work for parachains.
This PR adds the necessary mapping to `NormalizedRunCmd`
> fix: map cli option `--runtime_cache_size`

- .github/workflows/release-02_create-draft.yml
- .github/workflows/srtool.yml
We want srtool to be run on the `canvas-kusama` runtime so that it will be part of a release.
> Add Canvas runtime to release automation

- pallets/collator-selection/src/benchmarking.rs
resolves #1062 
This PR tries to fix the error by returning validator accounts in `register_validators` and using them in the `set_invulnerables` benchmarking.
> Fix panic in `pallet-collator-selection` benchmarking

- client/cli/src/lib.rs
Improves usability and avoids confusion, as the named flags implicitly include `--collator`
> Improve conflict detection between cli flags

- Cargo.lock
- client/relay-chain-inprocess-interface/src/lib.rs
- client/relay-chain-rpc-interface/Cargo.toml
- parachain-template/node/src/service.rs
- polkadot-parachains/src/service.rs
- Fixes #928 
- If someone starts a parachain full node, we now use `IsCollator::No`, but still start the overseer with the option introduced in https://github.com/paritytech/polkadot/issues/4763 
- update parking_lot to 0.12.0 which we use in other locations of this project
> Support running relay chain full node as non-collator

- parachain-template/runtime/src/xcm_config.rs
- polkadot-parachains/canvas-kusama/src/xcm_config.rs
- polkadot-parachains/statemine/src/xcm_config.rs
- polkadot-parachains/statemint/src/xcm_config.rs
- polkadot-parachains/westmint/src/xcm_config.rs
This PR aims to solve #920.
We change the `Trader`'s `WeightToFee` type parameter to each chain's `WeightToFee` struct that properly calculates and converts weight units into fees. Previously, it would do a 1-to-1 conversion between weight units and plancks.
> Use WeightToFee when calculating cost of each weight unit in XCM trader

- parachain-template/runtime/Cargo.toml
- polkadot-parachains/canvas-kusama/Cargo.toml
- polkadot-parachains/statemine/Cargo.toml
- polkadot-parachains/statemint/Cargo.toml
- polkadot-parachains/westmint/Cargo.toml
#1076 somehow broke the check-runtime-benchmarks CI after failing to merge as companion and being force merged.
> Make CI work

- scripts/benchmarks.sh
As suggested by comment [here](https://github.com/paritytech/cumulus/pull/1012): to use `--json-file`
> --json-file param is nicer.

- pallets/xcmp-queue/src/lib.rs
`swap` is defined on slice so we can use it here. (`mem::swap` would complain about borrowing the same thing)
> xcmp swap - express intent better

- scripts/ci/changelog/templates/change.md.tera
- scripts/ci/changelog/templates/debug.md.tera
- scripts/ci/changelog/templates/host_functions.md.tera
- scripts/ci/changelog/templates/template.md.tera
Also removes a bunch of empty lines for a nice output
> Skip runtime migrations for the client release

- scripts/ci/changelog/templates/runtime.md.tera
This PR renders the cumulus runtimes as:
```
🏋️ Runtime Size:		651.85 KB (667493 bytes)
🔥 Core Version:		statemine-601 (statemine-0.tx4.au1)
🗜 Compressed:			Yes: 77.07%
🎁 Metadata version:		V14
#️⃣ Blake2-256 hash:		0x107c1bfb7a0e0b1d5a9a283be8b7ce782672099ab2aa881392d141173748cf5d
📦 IPFS:			QmcziqCFvbFr8mh3oRPS1wWNMHZBgJDzsjMk1KDkw7DA6v
```
instead of the previous:
```
🏋️ Runtime Size:		651.85 KB (667493 bytes)
🔥 Core Version:		statemine-601 (statemine-0.tx4.au1)
🗜 Compressed:			Yes: 77.07%
🎁 Metadata version:		V14
🗳️ system.setCode hash:		0x9663230d1468b395ebc02f63da0efb3cb0acb97d920e8395afa2c5bf937e31f0
🗳️ authorizeUpgrade hash:	0x87131b07d387638df843a93a21b90b46cb44ab48c69ead728903ac134aef4a61
#️⃣ Blake2-256 hash:		0x107c1bfb7a0e0b1d5a9a283be8b7ce782672099ab2aa881392d141173748cf5d
📦 …
```
> Hide unwanted hashes for parachain runtimes

- Cargo.lock
The 0.7.4 version of the `lru` crate [has an important soundness fix](https://github.com/jeromefroe/lru-rs/commit/ec021658cd7d48deb88226ad31bb6f3f33e16575). (It's for a new API introduced in 0.7.3 so it doesn't affect us though, as nothing uses it anyway.)
Related polkadot PR: https://github.com/paritytech/polkadot/pull/5244 (can be merged after this PR is merged in)
> Bump `lru` to 0.7.4

- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
As https://github.com/paritytech/substrate/pull/10896 notes we need to bump the transaction version as there are breaking changes (not using compact representation for class or instance on uniques).
Fixes https://github.com/paritytech/cumulus/issues/1132
> Bump tx version due to substrate 10896

- Cargo.lock
- parachain-template/runtime/src/lib.rs
- polkadot-parachains/canvas-kusama/src/lib.rs
- polkadot-parachains/rococo-parachain/src/lib.rs
- polkadot-parachains/statemine/src/lib.rs
- polkadot-parachains/statemint/src/lib.rs
- polkadot-parachains/westmint/src/lib.rs
- test/runtime/src/lib.rs
This is a companion PR for paritytech/substrate#10785.
It refactors the runtimes to use `pallet-transaction-payment`s new `LengthToFee`. The fee structure should remain unchanged.
> Add LengthToFee to runtimes

- .gitlab-ci.yml
Fixed manual execution benchmarks from web, also added additional condition to run `Publish` only on `master` and tags `v*` from web
Part of https://github.com/paritytech/ci_cd/issues/260
> Fix rules for benchmarks and publish

- Cargo.lock
- client/relay-chain-inprocess-interface/src/lib.rs
- primitives/core/src/lib.rs
`ParachainHost` is no longer versioned and is in `runtime_api` module. Please refer to the PR below for further details.
This is a companion for https://github.com/paritytech/polkadot/pull/5048
> Handle relocation of `ParachainHost` in Polkadot

- .gitlab-ci.yml
With current rules the `publish` job will run on all branches if they are triggered manually. The PR fixes this and also removes  unnecessary `when: manual` on benchmark job so there is only one manual button for benchmarks.
Part of https://github.com/paritytech/ci_cd/issues/260
> [ci] Fix rules for release branches

- .gitlab-ci.yml
The `benchmarks-build` job didn't work, because `$CARGO_TARGET_DIR` variable was deleted
> [ci] Fix `benchmarks-build`

- .gitlab-ci.yml
The `$CARGO_TARGET_DIR` variable was removed which broke benchmarks job
> [ci] small fixes for benchmark jobs

- pallets/parachain-system/src/lib.rs
cc @bkchr sorry to bother you again about the same thing. When going to benchmark moonbase I realized that PersistedValidationData does not implement default for non-std builds, so we cannot really use unwrap_or_default. Instead I need to initialize manually each of the fields :(.
Here is the fix. I tested the benchmark and it works with this fix. Again, sorry for not realizing about this before!
> Default not implemented for non-std builds for PersistedValidationData

- README.md
It is a minor change but a beginner might be irritated or can call the build command in wrong path if the working path is not changed
> bash tutorial: change the working path after clone

- Cargo.lock
- parachain-template/node/src/command.rs
- polkadot-parachains/src/command.rs
- Use `POLKADOT_REFERENCE_HARDWARE` when running `benchmark machine`
This now allows to compare the hardware to the Polkadot spec.  
Companion for https://github.com/paritytech/substrate/pull/11270
Polkadot companion: https://github.com/paritytech/polkadot/pull/5386
> Co #11270: Update benchmark machine command

- .github/pr-custom-review.yml
This PR update `pr-custom-review` rules according to https://github.com/paritytech/ci_cd/issues/405
* removes mandatory approval by the @paritytech/core-devs team of CI files `.gitlab-ci.yml`, `.github/.*`, `scripts/ci/.*`
* introduces new approval rule for the CI related stuff  `.gitlab-ci.yml`, `.github/.*`, `scripts/ci/.*` by @paritytech/ci team
> [ci] update review rules

- Cargo.lock
- polkadot-parachains/canvas-kusama/src/contracts.rs
https://github.com/paritytech/substrate/pull/11372
> Companion for contracts dos vector fix

- Cargo.lock
- pallets/collator-selection/src/lib.rs
- parachain-template/node/src/command.rs
- polkadot-parachains/src/command.rs
https://github.com/paritytech/substrate/pull/10719
https://github.com/paritytech/polkadot/pull/4947
> Companion for Substrate #10719 (Into Account Truncating)

- Cargo.lock
- test/service/src/main.rs
This was merged: https://github.com/paritytech/cumulus/pull/1158 
After this change: https://github.com/paritytech/substrate/pull/10719
Causing cumulus compile errors.
This fixes that.
> Fix Cumulus Compile (into_account_truncating)

- parachains/README.md
- parachains/runtimes/assets/README.md
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/starters/shell/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
Each runtime in `parachains/runtimes` should have documentation with it justifying its existence. Many teams use this repo for many purposes (e.g. production Statemint, devex templates, Rococo testing). Having clear rationale for each runtime's existence should help avoid confusion like in https://github.com/paritytech/cumulus/pull/1223.
> Runtime Documentation

- .github/workflows/extrinsic-ordering-check-from-bin.yml
Context: due to the renaming of the client from `polkadot-collator` to `polkadot-parachain`, fetch the binaries conflicted with the `polkadot-parachain` folder of the repo. But checking out the repo is not required for this workflow.
No repo => no conflict :)
> deleted unnecessary repo checkout to fix fetch binary step

- .gitlab-ci.yml
This PR changes CI rules for benchmark jobs creation.
Resolves https://github.com/paritytech/ci_cd/issues/447
> CI change rule to run benchmarks

- .github/workflows/extrinsic-ordering-check-from-bin.yml
As it turned out we still do need to checkout a repo to be able to use scripts later in pipeline. That's why we need to introduce a temp dir where we download and run binary.
reverting changes from [1296](https://github.com/paritytech/cumulus/pull/1296)
> bringing back repo checkout and adding a temp dir to avoid name duplication between binary and repo dir

- pallets/xcm/src/lib.rs
This broke our build when we trying to use `sp-debug-derive/force-debug`
> use RuntimeDebug

- parachain-template/runtime/src/xcm_config.rs
- parachains/common/src/xcm_config.rs
- parachains/runtimes/assets/statemine/src/xcm_config.rs
- parachains/runtimes/assets/statemint/src/xcm_config.rs
- parachains/runtimes/assets/westmint/src/xcm_config.rs
Users and applications should use `teleport` to send DOT/KSM between the Relay Chain and Statemint.
A future improvement would be to recognise reserve locations for other assets, like parachain native assets, described in https://github.com/paritytech/cumulus/issues/1317
> Statemint Should Not Recognise DOT Reserves

- .github/workflows/release-01_branch-check.yml
- scripts/ci/github/check-rel-br
So far, the cumulus code releases (branches `polkadot-v*`) were not checked with the new `check-rel-br` script.
This PR changes that to add the extra check.
> Run the release branch check on the cumulus code releases as well

- Cargo.lock
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
- polkadot-parachain/Cargo.toml
As per planned runtime upgrade for runtime parachains we need to upgrade the version. 
For assets runtimes (statemint/e) it's known that we will need to bump `transaction_version` because of Uniques pallet changes.
> Upgrade spec_version to `9230` and bump `transaction_version` for assets parachains.

- pallets/xcm/src/lib.rs
Is a companion for paritytech/substrate#11631, but can be merged on its own.
> Derive MaxEncodedLen on cumulus_pallet_xcm::Origin

- parachains/runtimes/assets/statemine/src/constants.rs
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/constants.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/constants.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/constants.rs
This PR lowers all the deposits of Statemine, Statemint, Westmint, and Contracts-Rococo by 10x.
This was decided based on a high level analysis of the cost of NFT deposits compared to other platforms.
This can always be adjusted later back up if needed.
Also fixes an issue where `contracts-rococo` did not use Rococo deposits.
> Lower all Assets / NFT deposits by 10x

- client/cli/src/lib.rs
Upstream CLI args changes are not port to Cumulus
> Add upstream new args

- test/relay-validation-worker-provider/build.rs
I was seeing build errors on a patched repo.
Problem is that we append relative paths to a filepath. From what I see we want to use the workspace directory, not the 'Cargo.toml' path.
> Fix patch handling for `relay-validation-worker-provider` build script

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Use unit type implementation from frame for identity verifier trait.
> Polkadot collectives: use unit type impl for identity verifier

- polkadot-parachain/src/command.rs
- polkadot-parachain/src/service.rs
We intend to reuse this across chains (E.g. collectives-polkadot CGP).
> rename build_import_queue to not be statemint specific

- client/relay-chain-inprocess-interface/src/lib.rs
* Disable beefy for inprocess relay chain node
* Update client/relay-chain-inprocess-interface/src/lib.rs
Co-authored-by: Bastian Köcher <bkchr@users.noreply.github.com>
> Disable beefy for inprocess relay chain node (#1382)

- polkadot-parachain/src/command.rs
- polkadot-parachain/src/service.rs
We're going to reuse the same node construction for as many common good parachains as we can (unless there's a particular reason not to).
> rename now shared node creation function

- Cargo.lock
- parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
This is a companion PR for https://github.com/paritytech/substrate/pull/11501
> Companion for substrate#11501

- parachains/chain-specs/statemine.json
- parachains/chain-specs/statemint.json
A tutorial on Substrate Connect is being added to the Substrate Developer Hub: https://github.com/substrate-developer-hub/substrate-docs/pull/1122
It uses Statemint as example for Parachain, and a list of WebSocket-enabled bootnodes is necessary for Substrate Connect.
> add wss bootnodes to statemine/t chainspec

- .github/workflows/release-10_docker-manual.yml
- .github/workflows/release-10_docker.yml
With the recent refactoring, we now have a folder named like the binary we release and that causes troubles when fetching the artifacts from Github into the checked out repo.
To address this, tihs PR downloads the artifacts into a `tmp` folder.
> Fix Docker CI

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Use the ConstU32 types and friends where possible to have the least amount of code inside `parameter_types` macros.
Interestingly SS58Prefix is defined as a u8 and used as a u16. 
(If there was a `ConstBalance` type then that would remove the need for half the remaining `parameter_types` macros.)
> Less code in magic macros

- README.md
small things. Will do the same to substrate and polkadot if this gets approved so there's a consistent button to press in a pretty standard location.
> standard way to get at the docs

- Cargo.lock
Looks like the `polkadot-v0.9.24-1` branch is protected so I can't push this directly to it.
This just updates the Polkadot references to the latest commit on the [`release-v0.9.24-1`](https://github.com/paritytech/polkadot/compare/release-v0.9.24...release-v0.9.24-1?expand=1) branch.
> Bump lockfile for `polkadot-v0.9.24-1`

- client/cli/src/lib.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
related: https://github.com/paritytech/cumulus/pull/1325
> Use genesis_state_version param instead of StateVersion::V0

- client/cli/src/lib.rs
Signed-off-by: koushiro <koushiro.cqx@gmail.com>
> Use genesis_state_version param instead of StateVersion::V0 (#1410)

- Cargo.lock
- client/relay-chain-inprocess-interface/src/lib.rs
- docs/overview.md
- parachain-template/node/src/service.rs
- polkadot-parachain/src/service.rs
- test/service/src/lib.rs
Companion PR to https://github.com/paritytech/substrate/pull/11865
> Cleanup light client leftovers

- .gitlab-ci.yml
Currently timeout for all jobs is 1 day which is too much especially when a job hangs for some reasons. PR sets timeout 1 day only from benchmark job. For other jobs default timeout will be 2 hours (it's going to be set in repo settings)
https://github.com/paritytech/ci_cd/issues/543
> [ci] Add timeout to benchmark job

- .gitlab-ci.yml
PR improves `test-linux-stable` job and makes pipeline faster (nextest saves ~10 minutes)
> [ci] use nextest for tests

- test/relay-sproof-builder/src/lib.rs
Adds epoch index to RelayStateSproofBuilder
We are using this for testing in https://github.com/PureStake/moonbeam/pull/1376 and we have cherrypicked these changes on that branch
> Add epoch index to RelayStateSproofBuilder (for testing)

- parachains/runtimes/testing/rococo-parachain/src/lib.rs
Is there any underlaying reason to not have the TxVersion check as part of the signature payload in this particular test runtime? If not, then I would love to have it in, for consistency sake with most of runtime implementations.
> Adding TxVersion Check to signed params

- Cargo.lock
- client/relay-chain-interface/src/lib.rs
- client/relay-chain-rpc-interface/Cargo.toml
- client/relay-chain-rpc-interface/src/lib.rs
- client/relay-chain-rpc-interface/src/rpc_client.rs
- parachain-template/node/src/service.rs
- polkadot-parachain/src/service.rs
- test/service/src/lib.rs
This PR is the next step towards https://github.com/paritytech/cumulus/issues/989.
Currently the collator opens a new RPC subscription every time we request a notification stream from the `RelayChainRPCInterface`. 
After this PR is merged, we will have only three open notification subscriptionsvia RPC:
- finalized block headers
- imported block headers
- new best block headers
A worker is introduced that will poll these three subscriptions regularly and distribute the contained headers to all listening streams. Requesting a stream from the `RelayChainRPCInterface` will return a new channel and inform the worker.
Since the streams are only used in the collator, and we have complete control, we use bounded channels with a limit of 20 items.
> Introduce RPC Worker

- docs/release.md
Tiny typos I noticed while reading the docs. I'm pretty sure that 'senmver' was supposed to be 'semver' for semantic versioning, and 'versioning' was misspelled.
> Fix typos in release.md

- .gitignore
Git ignore dot-underscore.
Same pattern used as within [substrate](https://github.com/paritytech/substrate/blob/6401300a2ff7ce013385f2c61fc9a3798bd4272d/.gitignore#L10) and polkadot repos.
> gitignore dot-underscore

- Cargo.lock
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
- polkadot-parachain/Cargo.toml
…ets parachains. (#1340)
* Transaction version bump + updated spec_version
* Reformatting issue
* Adding missing runtimes
* Upgrading contracts pallet runtime version
* Upgrading Seedling runtime
* Bump polkadot-parachain version
Co-authored-by: Wilfried Kopp <wilfried@parity.io>
> Upgrade spec_version to `9230` and bump `transaction_version`

- .gitlab-ci.yml
The PR improves `test-linux-stable` job. Now it posts a message that the pipeline was cancelled and logs to the failed job.
I will remove `branch:                        "as-improve"` when adapt this job in polkadot and substrate.
cc https://github.com/paritytech/ci_cd/issues/548
> [ci] improve cancel-pipeline job

- scripts/ci/changelog/templates/runtime.md.tera
This backport is only relevant for the **runtimes** release branch and fixes the issue resulting in improperly showing `[object]` as version in the release notes.
> Backport core version fix

- scripts/ci/changelog/templates/change.md.tera
- scripts/ci/changelog/templates/changes_misc.md.tera
- scripts/ci/changelog/templates/changes_runtime.md.tera
- scripts/ci/changelog/templates/high_priority.md.tera
WIP: #1533 is required to be merged before we can merge this PR
Before merging, the following needs to be checked:
cc @the-right-joyce
> Fix release notes templates according to label changes in #1533

- scripts/ci/changelog/templates/changes.md.tera
- scripts/ci/changelog/templates/template.md.tera
Better version of https://github.com/paritytech/cumulus/pull/1470
Tested to make sure no change to node release notes. All new lines are present and accounted for.
no need for compiler version as we use srtool (saying the compiler version was confusing and misdirection).
no need for priority as that only makes sense for nodes.
no need for the duplication of the runtime hashes.
> Removes duplication and unneeded sections of runtime release notes

- Cargo.lock
- parachains/runtimes/assets/statemine/src/weights/pallet_uniques.rs
- parachains/runtimes/assets/statemint/src/weights/pallet_uniques.rs
- parachains/runtimes/assets/westmint/src/weights/pallet_uniques.rs
Partially reverts https://github.com/paritytech/cumulus/pull/1460  
Companion for https://github.com/paritytech/substrate/pull/12059
This removes the `Uniques::try_increment_id` extrinsic which should not be deployed anywhere yet.  
Could someone double check that?
> Co #12059: Revert "Auto-incremental CollectionId"

- .gitlab-ci.yml
The PR modifies the `benchmarks-statemint` job so it now can create 3 PRs: to `release-parachains-*`, `master` and `v*` branches.
Close https://github.com/paritytech/ci_cd/issues/572
> [ci] Weights PR for master and client on cumulus

- .gitlab-ci.yml
Bump zombienet, this new version set the baseline resources for pods in CI.
cc @bkchr.
> chore: bump zombienet version

- .github/workflows/docs.yml
- .github/workflows/release-30_create-draft.yml
In order to improve our security posture with GitHub Actions usage. I've made a version pinning ether to commit hash or to specific version.
Related issues and policy:
https://github.com/paritytech/ci_cd/issues/464
https://github.com/paritytech/ci_cd/wiki/Policies-and-regulations:-GitHub-Actions-usage-policies
Following actions from trusted vendors also pinned to specific verstion because their repositories are archived and no further development expected:
actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
> Pin GHA versions

- Cargo.lock
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Updating collectives runtime to support new version of alliance pallet.
Companion for Substrate PR https://github.com/paritytech/substrate/pull/11970
> Collectives runtime: alliance pallet upgrade introducing new retirement notice feature

- Cargo.lock
- parachains/runtimes/testing/penpal/Cargo.toml
- parachains/runtimes/testing/penpal/src/lib.rs
This has been released in 9270. ( https://github.com/paritytech/cumulus/commit/ba03538945fb6a41df56e5ccee2a550d747ad620 )
> 9270 Backport of Align versions for runtimes (#1517)

- parachains/integration-tests/statemine/xcm/0_init.yml
- parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
- parachains/integration-tests/statemine/xcm/4_hrmp.yml
- parachains/integration-tests/statemint/xcm/0_init.yml
- parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
- parachains/integration-tests/statemint/xcm/4_hrmp.yml
Backport of https://github.com/paritytech/cumulus/commit/e6c9c8b62f9f44d27ed4d0a6807b4a186ad37b25 to master
> 9270 Backport / Integration tests Statemine & Statemint (#1526)

- scripts/ci/changelog/bin/changelog
Error from "Generate release notes" - https://github.com/paritytech/cumulus/runs/8194727157?check_suite_focus=true
```
[2022-09-05T18:50:05.653663 #1757] DEBUG -- : Building changelog with runtimes
jq: error: syntax error, unexpected '{' (Unix shell quoting issues?) at <top-level>, line 12:
{ name: "polkadot-collectives", data: $srtool_polkadot_collectives[0] },            
jq: error: syntax error, unexpected ']' (Unix shell quoting issues?) at <top-level>, line 13:
] }      
jq: 2 compile errors
thread 'main' panicked at 'JSON parsing: Error("EOF while parsing a value", line: 1, column: 0)', src/wrapped_context.rs:40:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
-rw-r--r-- 1 runner docker 0 Sep  5 18:50 context.json
```
> fix release report generation script

- client/relay-chain-inprocess-interface/Cargo.toml
> Add right feature flags to `relay-chain-inprocess-interface`

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Changing the Collectives runtime version pattern to math with all other parachains within the repo.
> Common version pattern for Collectives runtime

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/starters/shell/src/lib.rs
- parachains/runtimes/testing/penpal/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
will be backported into draft-polkadot-v0.9.29 branch
> runtimes version to 9290

- Cargo.lock
- parachain-template/node/src/command.rs
- parachain-template/runtime/Cargo.toml
- parachains/runtimes/assets/statemine/Cargo.toml
- parachains/runtimes/assets/statemint/Cargo.toml
- parachains/runtimes/assets/westmint/Cargo.toml
- parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
- parachains/runtimes/contracts/contracts-rococo/Cargo.toml
- parachains/runtimes/testing/penpal/Cargo.toml
- polkadot-parachain/src/command.rs
- polkadot-parachain/tests/benchmark_storage_works.rs
Polkadot MR: https://github.com/paritytech/polkadot/pull/5983
Substrate MR: https://github.com/paritytech/substrate/pull/11976
> Co #11976: Enable rust features

- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
These halt the chain when invoked. Should have spotted it when reviewed #1454 .
> Don't panic.

- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
Cherry pick of https://github.com/paritytech/cumulus/pull/1629 to release branch
> Don't panic backported to release branch

- parachains/common/src/xcm_config.rs
- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Fixes issues with high teleport costs due to high multiplier for `Wild` assets, which is always the case with teleports. 
This is blocking the current release.
> [Fix] Weight calculations for Wild -> affects teleports

- parachains/common/src/xcm_config.rs
- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Reverts paritytech/cumulus#1639
Based on https://github.com/paritytech/cumulus/pull/1639#discussion_r974569345
> Revert "[Fix] Weight calculations for Wild -> affects teleports"

- .gitlab-ci.yml
The PR removes auto-fmt (reason: https://github.com/paritytech/ci_cd/issues/462#issuecomment-1252009270) and reverts cancel-pipeline job to an old version in order to change it (more info: https://github.com/paritytech/ci_cd/issues/548#issuecomment-1233436898)
> [ci] Disable auto-fmt and revert cancel-pipeline

- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
As per discussion with @KiChjang  and @joepetrowski .
> [Fix] Hardcode teleport weight until XCM pallet is fixed

- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
Cherrypick https://github.com/paritytech/cumulus/pull/1641 to node release branch.
> cherrypick teleport xcm fix to node rel branch

- .github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
the script - https://github.com/paritytech/cumulus/blob/master/scripts/ci/github/extrinsic-ordering-filter.sh
> fix a wrong path to Extrinsic Ordering ci script

- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
cherry-pick of https://github.com/paritytech/cumulus/pull/1651 from master to the runtime release branch.
* [Fix] Deposit weight hardcoded to pre-bench value
> cherrypick deposit asset xcm fix to runtime rel branch

- .gitlab-ci.yml
This small fix adds current time in millis to the name of the branch with weights to make it uniq and avoid issue when the re-ran job fails because the branch with the same name already exist
> Fix failing weights jobs

- Cargo.lock
- parachains/runtimes/assets/statemine/src/weights/pallet_proxy.rs
- parachains/runtimes/assets/statemint/src/weights/pallet_proxy.rs
- parachains/runtimes/assets/westmint/src/weights/pallet_proxy.rs
- parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
https://github.com/paritytech/substrate/pull/12283
https://github.com/paritytech/polkadot/pull/6038
> Companion for #12283 (Anon -> Pure Proxy)

- .gitlab-ci.yml
Other generated PRs have wrong base and drag additional commits into the generated PR.
Not a good idea as it turns out.
> fix weights PR generation

- .gitlab-ci.yml
Needed otherwise weights job fails due to branch already existing.
> backport: add current time in milis to the branch name (#1658)

- parachains/integration-tests/statemine/xcm/1_dmp.yml
- parachains/integration-tests/statemine/xcm/2_ump.yml
- parachains/integration-tests/statemine/xcm/3_hrmp-open-channels.yml
- parachains/integration-tests/statemine/xcm/4_hrmp.yml
- parachains/integration-tests/statemint/xcm/1_dmp.yml
- parachains/integration-tests/statemint/xcm/2_ump.yml
- parachains/integration-tests/statemint/xcm/3_hrmp-open-channels.yml
- parachains/integration-tests/statemint/xcm/4_hrmp.yml
backport from 9290 runtime branch. Introduces thresholds (yay!)
> backport: update integration tests

- pallets/collator-selection/src/benchmarking.rs
It's a minor PR to fix the error when benchmarking `pallet-collator-selection`, steps to reproduce:
1. clone the `cumulus` repo
2. `cargo build --features=runtime-benchmarks --release`
3. `./target/release/polkadot-parachain benchmark pallet --chain=statemine-dev --execution=wasm --db-cache=20 --pallet=pallet-collator-selection --extrinsic=* --steps=20 --repeat=50`
4. observe error from `pallet_collator_selection.register_as_candidate`: `Error: Input("TooManyCandidates")`
Problem is we try to register another candidate while having `MaxCandidates` candidates as the initial setup already. I didn't add extra comments as there's one already, but the code doesn't match.
> Minor fix of pallet-collator-selection benchmark error

- .github/workflows/release-10_rc-automation.yml
- .github/workflows/release-30_create-draft.yml
- .github/workflows/release-99_bot-announce.yml
This PR swaps the usage of secrets (which are no secrets) by workflow matrices so we can also notifity several rooms.
> Fix target of some Matrix notifications

- .github/workflows/fmt-check.yml
Close https://github.com/paritytech/cumulus/issues/1732
> [ci] add fmt check

- Cargo.lock
- pallets/dmp-queue/Cargo.toml
- pallets/dmp-queue/src/lib.rs
- pallets/dmp-queue/src/migration.rs
- pallets/xcmp-queue/src/benchmarking.rs
- pallets/xcmp-queue/src/lib.rs
- pallets/xcmp-queue/src/migration.rs
- pallets/xcmp-queue/src/tests.rs
- parachain-template/runtime/src/lib.rs
- parachains/common/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/starters/shell/src/lib.rs
- parachains/runtimes/testing/penpal/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
- test/runtime/src/lib.rs
Since migration to weights v2, we need to ensure that any pallets that store `Weight` structs or contain an extrinsic with a `Weight` parameter to migrate properly.
> Migrate Weights properly to v2

- Cargo.lock
- client/relay-chain-inprocess-interface/src/lib.rs
It changes the argument of `Backend::state_at` from:
`block: BlockId<Block>` to: `hash: &Block::Hash`
This PR is part of `BlockId::Number` refactoring analysis (https://github.com/paritytech/substrate/issues/11292) .
Companion for paritytech/substrate#12488
> BlockId removal refactor: Backend::state_at

- .github/workflows/check-labels.yml
- .github/workflows/docs.yml
- .github/workflows/fmt-check.yml
- .github/workflows/release-01_branch-check.yml
- .github/workflows/release-10_rc-automation.yml
- .github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
- .github/workflows/release-21_extrinsic-ordering-check-from-two.yml
- .github/workflows/release-30_create-draft.yml
- .github/workflows/release-50_docker-manual.yml
- .github/workflows/release-50_docker.yml
- .github/workflows/srtool.yml
- bump all GHA deps
- pin external GHA deps
⚠️ This PR should only be merged after https://github.com/chevdor/srtool-actions/pull/15 and once the `chevdor/srtool-actions@v0.6.0` tag has been created.
> GHA updates and pin

- .github/ISSUE_TEMPLATE/release-runtime.md
part of release process review initiative https://github.com/paritytech/cumulus/issues/1657
capturing the things discussed offline with release engineers and CGP team
> Runtime release checklist template update

- parachains/runtimes/contracts/contracts-rococo/Cargo.toml
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
This changes two things:
- We reduce the session length so we can change collators more quickly. 
- Enable unstable interfaces for contracts. This is a test net. We want to experiment with those new unstable interfaces here before stabilizing them. Even if that may brick already deployed contracts.
- Set `MinCandidates` to 0 to allow only invulnerables as collators. Otherwise no candidate can ever leave if there are not `5`others.
> contracts: Reduce session length and enable unstable interfaces

- Cargo.lock
- client/cli/Cargo.toml
- client/cli/src/lib.rs
- parachain-template/node/Cargo.toml
- parachain-template/node/src/cli.rs
- polkadot-parachain/Cargo.toml
- polkadot-parachain/src/cli.rs
- test/service/Cargo.toml
- test/service/src/cli.rs
Companion for https://github.com/paritytech/substrate/pull/12381
> Update clap to version 4

- Cargo.lock
- primitives/parachain-inherent/src/mock.rs
It changes the arguments of `Backend::StorageProvider` trait from:
block: `BlockId<Block>` to: hash: `&Block::Hash`
Companion for: paritytech/substrate#12510
> BlockId removal: refactor: StorageProvider

- parachain-template/node/src/command.rs
- parachain-template/node/src/service.rs
- polkadot-parachain/src/service.rs
Striving for simplicity, this PR removes some generics that are not really required in the template and thus reduces (at least a bit) some of the cognitive complexity required to understand the codebase by a new contributor
---
In particular here:
- some convenience type alias are defined
- remove generic `Runtime`. The parachain template is using only one runtime type
> Reduce parachain template cognitive complexity

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
Based on results of the extrinsic ordering check as part of the release checklist #1776
> bump transaction versions

- Cargo.lock
- parachain-template/node/Cargo.toml
- parachain-template/node/src/cli.rs
- parachain-template/node/src/command.rs
- parachain-template/runtime/Cargo.toml
- parachains/runtimes/assets/statemine/Cargo.toml
- parachains/runtimes/assets/statemint/Cargo.toml
- parachains/runtimes/assets/westmint/Cargo.toml
- parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
- parachains/runtimes/contracts/contracts-rococo/Cargo.toml
- parachains/runtimes/starters/shell/Cargo.toml
- parachains/runtimes/testing/penpal/Cargo.toml
- polkadot-parachain/Cargo.toml
- polkadot-parachain/src/cli.rs
- polkadot-parachain/src/command.rs
Companion for Substrate https://github.com/paritytech/substrate/pull/12341
Changes:
- Fix features to make it compile.
- Add dummy command that prints that try-runtime requires a feature, since right now it would not show up in `--help` anymore. That could impede discoverability.
> Co #12341: Use `try-runtime` feature

- Cargo.lock
- client/consensus/common/src/parachain_consensus.rs
It changes the arguments of methods of `Finalizer` trait from: block:
`BlockId<Block>` to: hash: `&Block::Hash`
This PR is part of BlockId::Number refactoring analysis (paritytech/substrate#11292)
Companion for: paritytech/substrate#12528
> BlockId removal: refactor: Finalizer

- Cargo.lock
- client/consensus/aura/src/import_queue.rs
- client/consensus/aura/src/lib.rs
- client/consensus/relay-chain/src/import_queue.rs
- client/consensus/relay-chain/src/lib.rs
- parachain-template/node/src/command.rs
- parachain-template/node/src/service.rs
- polkadot-parachain/src/service.rs
- primitives/parachain-inherent/src/mock.rs
- test/service/src/lib.rs
This PR allows to share a single `ParachainBlockImport` instance between the import queue and authoring engine, thus to have a shared state between the two components.
The implementation roughly follows the same design already used by Substrate node components.
---
The feature will be immediately used by https://github.com/paritytech/cumulus/pull/1559
> Single ParachainBlockImport instance

- zombienet_tests/0002-pov_recovery.feature
- zombienet_tests/0002-pov_recovery.toml
Add some nodes that use external relay chain node to the pov-recovery test
closes #1744
> Add RPC nodes to pov-recovery test

- Cargo.lock
- client/consensus/common/src/parachain_consensus.rs
- client/relay-chain-inprocess-interface/src/lib.rs
- primitives/parachain-inherent/src/mock.rs
It changes &Block::Hash argument to Block::Hash.
This PR is part of BlockId::Number refactoring analysis (paritytech/substrate#11292)
Companion for: paritytech/substrate#12626
> BlockId removal: &Hash to Hash

- .gitlab-ci.yml
- scripts/ci/gitlab/pipeline/zombienet.yml
This PR fixes failing GitLab CI pipeline the same as #1836 but for the client part
> fix failing gitlab ci pipelien

- scripts/ci/gitlab/pipeline/benchmarks.yml
- scripts/ci/gitlab/pipeline/publish.yml
PR fixes publishing benchmarks results for `release-parachains-v*` branches
cc https://github.com/paritytech/ci_cd/issues/468
> [ci] Fix publish benchmark results

- .gitlab-ci.yml
This PR backports #1786 and bumps zombienet version to fix failing test
> [Backport] #1786 to fix failing zombienet test

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
According to the [Extrinsic ordering check](https://github.com/paritytech/cumulus/issues/1844#issuecomment-1309050901) transaction_version needs to bumped
> bump txn versions

- Cargo.lock
This RPR updates substrate .32 deps to the latest state
> update substrate deps to the latest state

- parachain-template/node/src/service.rs
See relevant [StackExchange](https://substrate.stackexchange.com/questions/5726/offchain-worker-not-initializing-cumulus-parachain-template) question.
We were developing on the Substrate Parachain Template, and couldn't figure out why offchain workers were not initializing. From my POV, this should be enabled here, just as it is on the Substrate Node Template. Opening up a PR to save others time in the future and prevent them from running into a similar issue.
> Add Offchain Worker to Parachain Config by Default

- scripts/ci/changelog/templates/docker_image.md.tera
- scripts/ci/changelog/templates/template.md.tera
The Docker section was already in the reklease notes but it was not visible by default and also not restricted to the client releases.
This PR enables the docker section in the release notes, for the client releases only.
> Enable Docker section in the release notes

- scripts/ci/gitlab/pipeline/publish.yml
This pr backports rollback of the buildah to fix failing ci pipeline
> [Backport] fix buildah (#1870)

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/testing/penpal/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
This PR backports bumps of the `spec_version` of the penpal and rococo runtimes and `transaction_version` from release v9320
> [Backport] bump spec and txn versions from v9320

- Cargo.toml
- pallets/solo-to-para/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
related PR: https://github.com/paritytech/substrate/pull/12496
> Use pallet-sudo extension `CheckOnylSudoAccount`

- parachain-template/runtime/src/xcm_config.rs
- parachains/common/src/xcm_config.rs
- parachains/runtimes/testing/penpal/src/xcm_config.rs
> https://github.com/paritytech/cumulus/pull/1169#discussion_r1022773741
> Correct issue link

- parachains/runtimes/bridge-hubs/README.md
- parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Resolves https://github.com/paritytech/parity-bridges-common/issues/1662
Updating the README in order to use the `relay-headers-and-messages` command.
> Use the `relay-headers-and-messages` command

- Cargo.lock
- parachains/runtimes/collectives/collectives-polkadot/src/impls.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
Companion for https://github.com/paritytech/substrate/pull/12730
> Collectives Alliance: Remove Founder role and veto call

- polkadot-parachain/src/command.rs
- polkadot-parachain/src/service.rs
We forgot to add contract to the `try-runtime` CLI.
> Allow try-runtime for contracts-rococo

- parachains/common/src/xcm_config.rs
- parachains/runtimes/assets/statemine/src/xcm_config.rs
- parachains/runtimes/assets/statemine/tests/tests.rs
- parachains/runtimes/assets/statemint/src/xcm_config.rs
- parachains/runtimes/assets/statemint/tests/tests.rs
- parachains/runtimes/assets/westmint/src/xcm_config.rs
- parachains/runtimes/assets/westmint/tests/tests.rs
- primitives/utility/src/lib.rs
fixes: https://github.com/paritytech/cumulus/issues/1884
> Allow Sufficient Assets for XCM Fee Payment on Statemint #1884

- Cargo.lock
- parachains/runtimes/contracts/contracts-rococo/Cargo.toml
- parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
https://github.com/paritytech/substrate/pull/12787
> Companion for contracts: Replace cargo feature `unstable-interface` with config

- Cargo.lock
- client/relay-chain-minimal-node/Cargo.toml
- client/relay-chain-minimal-node/src/network.rs
These request-response protocols were previously required, but for some time now, they have been optional.
For the minimal Polkadot node we do not need them.
> Remove block request, state request, light client request-response protocols from minimal node

- parachains/runtimes/testing/penpal/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
This PR bumps spec_version for rococo and penpal
> bump rococo and penpal spec_version

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
This PR bumps transaction versions based on the extrinsic ordering check.
Results can be found in [the release checklist](https://github.com/paritytech/cumulus/issues/1925#issuecomment-1335475660)
> bump transaction_versions client

- scripts/ci/gitlab/pipeline/zombienet.yml
- Store log information in artifacts so external contributors can access those if their are needed for debugging.
Thanks!
> `zombienet` store node's logs as artifacts

- Cargo.lock
- client/consensus/common/Cargo.toml
- client/consensus/common/src/parachain_consensus.rs
- client/consensus/common/src/tests.rs
- client/pov-recovery/src/active_candidate_recovery.rs
- client/pov-recovery/src/lib.rs
- client/service/Cargo.toml
- client/service/src/lib.rs
- primitives/core/src/lib.rs
This PR augments https://github.com/paritytech/cumulus/pull/1559 with block recovery via PoV.
(target branch has been set to https://github.com/paritytech/cumulus/pull/1559 branch in order to better highlight the diff and have a more  focused conversation)
---
A recovery channel end is passed to the parachain consensus worker and it is used to trigger/stimulate block recovery whenever the best parachain block is not locally present yet.
The rx side of the channel can be whatever and not strictly necessarily the PoV recovery mechanism.
This code is very unlikely from being triggered in practice. But better safe than sorry.
---
The tests were not aligned yet to some  of the new interfaces, so CI failure is expected.  Feedback first :-)
> Explicit recovery for announced candidate blocks

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
Adding the rpc calls to query weight and fee details of a Call.
> Collectives runtime: weight and fee info rpc for Call 

- Cargo.lock
- parachain-template/node/Cargo.toml
- parachain-template/node/src/command.rs
- parachain-template/runtime/src/lib.rs
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/penpal/src/lib.rs
- polkadot-parachain/src/command.rs
https://github.com/paritytech/polkadot/pull/6187
https://github.com/paritytech/substrate/pull/12537
> companion for try-runtime revamp

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
This PR backports txn versions bump from polkadot-v0.9.36
> Backport: bump txn versions (#2018) to runtimes release branch

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
PR backports txn versions bump from polkadot-v0.9.36
> Backport: bump txn versions (#2018)

- Cargo.lock
- parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
Companion for https://github.com/paritytech/substrate/pull/13001
> Alliance: remove veto weight func

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
This PR backports old migration deletion from the release runtimes branch to the release node branch
> Backport: remove 9330 migrations from statemint series (#2031) to node branch

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
This PR backports old migration deletion from the release runtimes branch to the release source branch
> Backport: remove 9330 migrations from statemint series (#2031) to the source branhc

- Cargo.lock
- Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
This pallet is used by our testnets for selecting different validators in each session (without staking and everything else). It shall not be used in production.
Nothing criminal - just extra code :)
> remove shift session manager from bridge-hub-rococo

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
This PR backports removed 9330 migrations from release 9360 to master
> Backport: remove 9330 migrations from statemint series (#2031) to master

- Cargo.lock
- parachain-template/runtime/src/lib.rs
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/penpal/src/lib.rs
Companion for https://github.com/paritytech/polkadot/pull/6498 and https://github.com/paritytech/substrate/pull/13045
> Co #6498: Selectable on-runtime-upgrade checks

- Cargo.lock
Bump asyncronous-codec, futures-rustls, rustls, ipnet and once_cell crate versions (companion to https://github.com/paritytech/substrate/pull/12734).
> upgrade libp2p to 0.50.0

- Cargo.lock
- client/consensus/common/src/parachain_consensus.rs
- client/consensus/common/src/tests.rs
- client/network/Cargo.toml
- client/network/src/tests.rs
- client/relay-chain-interface/src/lib.rs
It was just some historical trait that isn't really required anymore. Besides that this pr re-exports types that are being used by the relay chain interface to make its usage easier.
> Remove the `RelaychainClient` trait

- README.md
- parachains/README.md
> Minor update to Readme - Statemint section

- Cargo.lock
This PR backports dependencies update of polkadot from runtimes release branch `release-parachains-v9370` into the source release branch `polkadot-v0.9.37`
> [Backport] of update polkadot dependencies (#2086)

- Cargo.lock
Thi PR backports polkadot dependencies update from runtime release branch `release-parachains-v9370` into to the client release branch `release-v0.9.370`
> [Backport] of update polkadot dependecies (#2086)

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
These were in [v9360](https://github.com/paritytech/cumulus/blob/release-parachains-v9360/parachains/runtimes/collectives/collectives-polkadot/src/lib.rs#L566)
> Remove 9360 migrations

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
This PR contains backport of the removed 9360 migrations from runtime release branch `release-parachains-v9370`
> [backport] remove collectives migrations (#2103) from runtime release branch

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
This PR contains backport of the 9360 migrations removal from runtimes rlease branch `runtime-parachains-v9370`
> [backport] remove 9360 collectives migrations (#2103)

- Cargo.lock
- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemine/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/mod.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/pallet_xcm_benchmarks_generic.rs
Companion for paritytech/polkadot#6578
> Companion for paritytech/polkadot#6578

- client/relay-chain-rpc-interface/src/rpc_client.rs
The runtime function name doesn't change on chain, especially not for old runtimes.
> Use correct runtime function name

- Cargo.lock
- bridges/bin/runtime-common/src/integrity.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_rococo_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_hub_wococo_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
Fixes: https://github.com/paritytech/parity-bridges-common/issues/1672
Posting this PR as a draft for the moment because of the issues described [here](https://github.com/paritytech/parity-bridges-common/issues/1672#issuecomment-1344089520).
> Add Rococo <> Wococo integrity tests

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
This PR contains a backport of the removal of an old migrations from release 9370 to master
> [Backport] remove collectives migrations (#2103) from 9370

- Cargo.lock
- pallets/xcmp-queue/Cargo.toml
- parachains/runtimes/contracts/contracts-rococo/Cargo.toml
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/Cargo.toml
Companion for https://github.com/paritytech/substrate/pull/13301
> Co #13301: Rename `pallet-random-collective-flip`

- Cargo.lock
- parachains/runtimes/testing/rococo-parachain/Cargo.toml
the change was included into master here https://github.com/paritytech/cumulus/pull/2159
> fix: enable runtime-benchmarks feature for xcm-builder

- Cargo.lock
This PR backports polkadot deps update from runtime release branch to the source release branch
> [backport] Update polkadot dependencies (#2183) to the source branch

- Cargo.lock
This PR backports polkadot deps update from runtime release branch to the node release branch
> [backport] Update polkadot dependencies (#2183) to node release branch

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
This PR bumps txn versions based on the extrinsic ordering check from #2163
> bump transaction_version

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
- scripts/ci/changelog/bin/changelog
This PR backports `transaction_version` bump and fix for changelog from runtimes release brunch
> [backport] txn version bump and changelog fix

- parachains/chain-specs/bridge-hub-kusama.json
- parachains/chain-specs/collectives-westend.json
Hello,
Requesting to add our bootnodes to collectives-westend and bridge-hub-kusama. 
Thanks!
> Add stake.plus bootnodes to collectives-westend and bridge-hub-kusama

- scripts/ci/changelog/Gemfile
- scripts/ci/changelog/Gemfile.lock
- scripts/ci/changelog/bin/changelog
- scripts/ci/changelog/templates/change.md.tera
- scripts/ci/changelog/templates/changes.md.tera
- scripts/ci/changelog/templates/changes_api.md.tera
- scripts/ci/changelog/templates/changes_client.md.tera
- scripts/ci/changelog/templates/changes_misc.md.tera
- scripts/ci/changelog/templates/changes_runtime.md.tera
- scripts/ci/changelog/templates/debug.md.tera
- scripts/ci/changelog/templates/high_priority.md.tera
- scripts/ci/changelog/templates/host_functions.md.tera
- scripts/ci/changelog/templates/migrations-db.md.tera
- scripts/ci/changelog/templates/migrations-runtime.md.tera
Same than https://github.com/paritytech/polkadot/pull/6702
> WIP: Fix templates

- Cargo.lock
- client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
- client/relay-chain-minimal-node/src/network.rs
- client/relay-chain-rpc-interface/src/rpc_client.rs
- parachain-template/node/src/command.rs
- polkadot-parachain/src/command.rs
Companion for paritytech/polkadot#6744
Removes support for the outdated `OldV1SessionInfo` structure and respective runtime client calls.
> Companion for paritytech/polkadot#6744: Retire `OldV1SessionInfo`

- Cargo.lock
- test/client/src/block_builder.rs
It changes the arguments of `BlockBuilderProvider::new_block_at` from:
`BlockId<Block>` to: `Block::Hash`
This PR is part of BlockId::Number refactoring analysis (https://github.com/paritytech/substrate/issues/11292)
Companion for: paritytech/substrate#13401
> `BlockId` removal: `BlockBuilderProvider::new_block_at`

- parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Allow the executing of Alliance::init_member and XcmPallet::force_xcm_version via XCM Transact operation.
This is nice to have, both calls required for the integration tests https://github.com/paritytech/cumulus/pull/2221.
> Collectives chain xcm filter

- .gitlab-ci.yml
- zombienet/tests/0001-sync_blocks_from_tip_without_connected_collator.zndsl
- zombienet/tests/0002-pov_recovery.zndsl
- zombienet/tests/0003-full_node_catching_up.zndsl
- zombienet/tests/0004-runtime_upgrade.zndsl
- zombienet/tests/0005-migrate_solo_to_para.zndsl
- zombienet/tests/0006-rpc_collator_builds_blocks.zndsl
- zombienet/tests/0007-full_node_warp_sync.zndsl
Bump zombienet version and removing the is up assertions since that is now checked by zombienet before running the tests.
Thanks!
> bump `zombienet` version to v1.3.35

- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/tests.rs
Adds checks to ensure that the spec version is increasing and that the spec name is the same. This will prevent accidentally upgrading a parachain to a different runtime.
Although this changes storage, I did not increase the storage version or provide a migration. The reason is that the upgrade itself will `kill` the affected storage item, and the next time an upgrade is authorized, the new type will be written. But this will break any front ends that show authorized upgrades, so let me know if I should bump the storage version for this.
Unfortunately breaks it, although it's a Root call. Could also add a new function `authorize_upgrade_without_checks` as an alternative.
> Add Version Checks on Para Upgrade

- pallets/parachain-system/src/lib.rs
This will allow parachains to read the relay chain state via storage proofs.
> introduce RelaychainStateProvider to parachain-system

- parachains/runtimes/assets/statemine/src/xcm_config.rs
- parachains/runtimes/assets/statemint/src/xcm_config.rs
- parachains/runtimes/assets/westmint/src/xcm_config.rs
Same as https://github.com/paritytech/cumulus/pull/2222 but for statemine/t.
> [Fix] Allow force_xcm_version call for assets parachains

- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
- parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
Supplement to https://github.com/paritytech/cumulus/pull/2276
> Add `force_xcm_version` to Other Runtimes

- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
(Same as assets and collectives)
> bridgehub force xcm version safe

- parachain-template/runtime/src/xcm_config.rs
- parachains/common/src/xcm_config.rs
This is a follow up to paritytech/polkadot#6756 to switch all barriers into using the matcher API for writing its conditionals.
> XCM: Use matcher API in DenyReserveAssetTransferToRelay

- pallets/collator-selection/src/lib.rs
- pallets/dmp-queue/src/lib.rs
- pallets/dmp-queue/src/migration.rs
- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/migration.rs
- pallets/solo-to-para/src/lib.rs
- pallets/xcm/src/lib.rs
- pallets/xcmp-queue/src/lib.rs
- pallets/xcmp-queue/src/migration.rs
- parachain-template/pallets/template/src/lib.rs
- parachains/pallets/parachain-info/src/lib.rs
- parachains/pallets/ping/src/lib.rs
- test/runtime/src/test_pallet.rs
Substrate companion https://github.com/paritytech/substrate/pull/13535
> Remove use of trait Store

- Cargo.lock
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
- polkadot-parachain/Cargo.toml
This PR backports `crate_version` and `transaction_version` bumps from 9380 release
> [Backport] version bumps from 9380

- parachains/runtimes/assets/statemine/src/xcm_config.rs
- parachains/runtimes/assets/statemint/src/xcm_config.rs
- parachains/runtimes/assets/westmint/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
- parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
(Same as assets and collectives)
Backport of https://github.com/paritytech/cumulus/pull/2288 , #2276 , #2284
(They're rolled into one PR as they are conceptually one change)
> Backport: Brigehub: Add in force upgrade xcm version (into master)

- README.md
Some comments did not make it in time in https://github.com/paritytech/cumulus/pull/2313.
- Lines are now approx. 100 characters long.
- ran this through the spellchecker again and improved clarity.
- Removed the comments in the code snippets, maybe was unnecessary to begin with, the text describes the options already
- relaychain -> relay chain
> ReadMe followup for  #2313

- scripts/bridges_rococo_wococo.sh
Related to https://github.com/paritytech/parity-bridges-common/issues/1840
Couple of issues:
- `node`' exit code is overwritten and `generate_hex_encoded_call_data` always returns zero;
- after fixing it ^^^, we're doing `npm install` and then `exit 1`.
Example docker that uses updated script:
```dockerfile
FROM docker.io/paritytech/polkadotjs-cli:latest
RUN mkdir -p /data/scripts/generate_hex_encoded_call
RUN wget -O /data/scripts/generate_hex_encoded_call/index.js https://raw.githubusercontent.com/paritytech/cumulus/f0657dab3439f2b315493b8a044e957618645cc0/scripts/generate_hex_encoded_call/index.js
RUN wget -O /data/scripts/generate_hex_encoded_call/package.json https://raw.githubusercontent.com/paritytech/cumulus/f0657dab3439f2b315493b8a044e957618645cc0/scripts/generate_hex_encoded_call …
```
> Fixed npm install call

- Cargo.lock
- client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
- client/relay-chain-rpc-interface/src/rpc_client.rs
Companion for paritytech/polkadot#6885
> Release parachain host API v4

- .gitlab-ci.yml
cf https://github.com/paritytech/ci_cd/issues/715
> timestamp ci job logs

- parachains/runtimes/assets/common/src/lib.rs
- parachains/runtimes/assets/common/src/matching.rs
- parachains/runtimes/assets/statemine/src/xcm_config.rs
- parachains/runtimes/assets/westmint/src/xcm_config.rs
Addressing https://github.com/paritytech/cumulus/pull/2167#discussion_r1138349663
> Added `StartsWithExplicitGlobalConsensus` to ignores

- Cargo.lock
- client/consensus/aura/src/lib.rs
- client/network/src/tests.rs
- parachain-template/node/src/service.rs
- polkadot-parachain/src/service.rs
- test/service/src/lib.rs
Companion for https://github.com/paritytech/substrate/pull/13615
> [Companion  #13615] Keystore overhaul

- parachain-template/runtime/Cargo.toml
- parachain-template/runtime/build.rs
- parachains/runtimes/assets/statemine/Cargo.toml
- parachains/runtimes/assets/statemine/build.rs
- parachains/runtimes/assets/statemint/Cargo.toml
- parachains/runtimes/assets/statemint/build.rs
- parachains/runtimes/assets/westmint/Cargo.toml
- parachains/runtimes/assets/westmint/build.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/build.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/build.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/build.rs
- parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
- parachains/runtimes/collectives/collectives-polkadot/build.rs
- parachains/runtimes/contracts/contracts-rococo/Cargo.toml
- parachains/runtimes/contracts/contracts-rococo/build.rs
- parachains/runtimes/starters/seedling/Cargo.toml
- parachains/runtimes/starters/seedling/build.rs
- parachains/runtimes/starters/shell/Cargo.toml
- parachains/runtimes/starters/shell/build.rs
- parachains/runtimes/testing/penpal/Cargo.toml
- parachains/runtimes/testing/penpal/build.rs
- parachains/runtimes/testing/rococo-parachain/Cargo.toml
- parachains/runtimes/testing/rococo-parachain/build.rs
- test/runtime/Cargo.toml
- test/runtime/build.rs
There is no need to compile wasm-builder in `no_std` as we skip the compilation of the crate any way. So, we can also directly disable wasm-builder as dependency in `no_std` to improve build times.
> Improve build times by disabling wasm-builder in `no_std`

- client/cli/src/lib.rs
- client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
closes #2337
The jsonrpsee websocket client always expects a port. However, the `url` crate always strips away the default port.
Sadly I did not find a way to force the `url` crate always to include a port into the URL, so I have to resort to manual string formatting.
> Always pass port to jsonrpsee WebSocket client

- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
This PR backports txn versions bump from runtimes release branch to the client release branch
> [Backport ]bump transaction versions (#2364) - client

- Cargo.lock
- parachain-template/runtime/src/xcm_config.rs
- parachains/runtimes/assets/statemine/src/xcm_config.rs
- parachains/runtimes/assets/statemint/src/xcm_config.rs
- parachains/runtimes/assets/westmint/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
- parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
- parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
- parachains/runtimes/testing/penpal/src/xcm_config.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
This is a companion PR for https://github.com/paritytech/polkadot/pull/6928.
> Companion for polkadot#6928

- Cargo.lock
- polkadot-parachain/src/service.rs
Companion for https://github.com/paritytech/substrate/pull/13683
Due to trivial renaming of 'AppKey' to 'AppCrypto' 😭 💡
> Companion for #13683

- Cargo.lock
- client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
- client/relay-chain-minimal-node/src/lib.rs
- client/relay-chain-minimal-node/src/network.rs
Get rid of HeaderBackend implementation and finally remove blocking calls.
companion for https://github.com/paritytech/substrate/pull/13730
> Remove HeaderBackend from RelayChainRPCClient

- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemine/tests/tests.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/tests/tests.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/tests/tests.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/mod.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/mod.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
This PR reverts changes made in #2102 because of https://github.com/paritytech/cumulus/issues/2392
> [Revert] Use XCM V3 for initiate_teleport weight calc #2102

- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemine/tests/tests.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/tests/tests.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/tests/tests.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/mod.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/mod.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
This PR backports #2394 from the runtimes release branch to the client release branch
> [Backport] of [Revert] Use XCM V3 for initiate_teleport weight calc #2102 (#2394) to client

- parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemine/tests/tests.rs
- parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/statemint/tests/tests.rs
- parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs
- parachains/runtimes/assets/westmint/tests/tests.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/weights/xcm/mod.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/weights/xcm/mod.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs
This PR backports #2394 from the runtimes release branch to the source release branch
> [Backport] [Revert] Use XCM V3 for initiate_teleport weight calc #2102 (#2394) source

- test/relay-sproof-builder/src/lib.rs
Currently, in order to write some tests that use storage keys that are not supported by the `RelayStateSproofBuilder` the only solution is to duplicate that struct in our code and add the additional fields. This PR aims to avoid that code duplication by adding an `additional_key_values` field to `RelayStateSproofBuilder`, such that it can be easily extended.
> Allow arbitrary key-values in RelayStateSproofBuilder

- client/consensus/common/src/level_monitor.rs
- client/consensus/common/src/tests.rs
Partially address https://github.com/paritytech/substrate/issues/13864
---
The reconstruction of the level monitor used by cumulus was using the `tree_route` function.
While this function perfs are acceptable for single very long branches (tested with a branch with an order of 3M with time ~2s on my "humble" machine). The limits hits when there are several leaves (tested with ~2K leaves).
Using this function to reconstruct the monitor computes all the 2K routes. Even if these are just small branches composed of 1 single block.
---
This PR adopts the strategy of stopping the backtrack as soon as we hit something already imported (i.e. we hit an already imported branch).
---
With this modification we should manage all the scenarios that realistically we find in the wild.
(obviously the …
> Optimize level monitor reconstruction

- Cargo.lock
- test/relay-validation-worker-provider/Cargo.toml
- test/relay-validation-worker-provider/build.rs
- test/relay-validation-worker-provider/src/lib.rs
PR: https://github.com/paritytech/polkadot/pull/7101
> [Polkadot Companion] for 7101

- .gitlab-ci.yml
- scripts/ci/gitlab/pipeline/publish.yml
PR updates buildah command and version. More info can be found in https://github.com/paritytech/ci_cd/issues/779
> [ci] Update buildah command and version

- Cargo.lock
- pallets/parachain-system/Cargo.toml
- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/relay_state_snapshot.rs
- pallets/parachain-system/src/tests.rs
- pallets/parachain-system/src/unincluded_segment.rs
- primitives/parachain-inherent/src/client_side.rs
- test/relay-sproof-builder/src/lib.rs
> (async backing) parachain-system: track limitations for unincluded blocks

- .github/workflows/fmt-check.yml
Current GHA uses latest nightly cargo fmt which might be unexpected when the version is changed. PR changes GHA to be run in `paritytech/ci-linux` docker image.
> [ci] Run gha fmt in docker

- Cargo.lock
- parachains/runtimes/contracts/contracts-rococo/src/contracts.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
Companion for paritytech/substrate/pull/13807
> Companion PR for add events to ContractResult

- Cargo.lock
This PR backports update of the substrate and polkadot deps to the source release branch
> [Backport] Update polkadot dependencies (#2515) to the source release branch

- parachains/chain-specs/contracts-rococo.json
After the migration of Rococo Contracts nodes to a new infrastructure DNS names have changed. Reflect the changes in the chainspec.
> Update DNS names of Rococo Contracts bootnodes

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
This PR backports `transaction_version` bump for `Collectives`  from the runtimes release branch
> [Backport] Bump transaction_version (#2520) to the client release branch

- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
This PR backports `transaction_version` bump for `Collectives`  from the runtimes release branch
> [Backport] Bump transaction_version (#2520) to the source release branch

- scripts/ci/gitlab/pipeline/zombienet.yml
Zombienet tests are still allowed to fail. Since the other tests have been removed for a while, let's make them mandatory.
> Make zombienet tests required

- parachains/runtimes/assets/statemine/src/xcm_config.rs
- parachains/runtimes/assets/westmint/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
- parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
This PR backports changes made in #2537 from the runtimes release branch to the source release branch
> [Backport] add set_invulnerables to SafeCallFilter (#2537) to source release branch

- parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
This pull request aligns the base weights for Collectives' XCM weighers with those of Polkadot.
The change to Polkadot's base weights has been made in this pull request - https://github.com/paritytech/polkadot/pull/7081.
> Collectives: xcm base weights

- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/tests.rs
- primitives/core/src/lib.rs
**After runtimes update to incorporate this PR, parachains using `pallet-parachain-system` will include a new digest in every header indicating their relay-parent's state root and number. Later on, this digest is intended to change to the relay-parent hash.**
Partially addresses #303 in the absence of https://github.com/paritytech/polkadot/issues/7191 .
This introduces a (currently unused) `CumulusDigestItem` which will have the relay-parent hash once that's available. In the meantime, there is a `#[doc(hidden)]` digest item representing the relay-parent storage root. This serves as a good enough unique identifier to implement https://github.com/paritytech/cumulus/issues/2476 .
For consideration - adding this private digest is not ideal, but it does let us implement some much better logic …
> Relay-parent digest logs for parachains

- Cargo.lock
- client/collator/Cargo.toml
- client/collator/src/lib.rs
- client/consensus/common/Cargo.toml
- client/consensus/common/src/tests.rs
- pallets/aura-ext/Cargo.toml
- pallets/aura-ext/src/consensus_hook.rs
- pallets/aura-ext/src/lib.rs
- pallets/parachain-system/src/consensus_hook.rs
- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/relay_state_snapshot.rs
- pallets/parachain-system/src/tests.rs
- pallets/parachain-system/src/unincluded_segment.rs
- pallets/parachain-system/src/validate_block/tests.rs
- pallets/xcmp-queue/src/mock.rs
- parachain-template/runtime/src/lib.rs
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/starters/seedling/src/lib.rs
- parachains/runtimes/starters/shell/src/lib.rs
- parachains/runtimes/testing/penpal/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
- primitives/timestamp/src/lib.rs
- test/runtime/src/lib.rs
This introduces the notion of a `ConsensusHook` for managing the unincluded segment capacity and performing consensus-specific checks. We'll provide some basic hooks, including an `ExpectParentIncluded` hook which is used to smooth over any transition periods where the collators aren't yet posting the included block's hash.
The idea is that we can write a custom `ConsensusHook` for the logic described in #2476 (probably fixed velocity=1, capacity=2/4, enforces max velocity + 1 blocks per slot).
I also fixed a bug in UMP queue size calculation and fixed some tests accordingly. Also relaxed the watermark rules to make them make sense, related to https://github.com/paritytech/polkadot/pull/7188
The vision with the consensus hook is something like this: it will be able to handle the …
> refactor unincluded segment length into a ConsensusHook

- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/tests.rs
- pallets/parachain-system/src/unincluded_segment.rs
> parachain-system: ignore go ahead signal once upgrade is processed

- parachains/integration-tests/emulated/common/src/constants.rs
If people are using zombienet with a relay chain that has sudo added to it (for testing) then this is one additional place that `sudo: Default::default()` does not need to be added (it's sufficient to add the sudo pallet to the polkadot repo E.g. the `-fast-sudo` branches).
> Use default for intergration test relay runtimes

- Cargo.lock
- Cargo.toml
- parachains/integration-tests/emulated/assets/statemine/Cargo.toml
- parachains/integration-tests/emulated/assets/statemine/src/lib.rs
- parachains/integration-tests/emulated/assets/statemine/src/tests/mod.rs
- parachains/integration-tests/emulated/assets/statemine/src/tests/reserve_transfer.rs
- parachains/integration-tests/emulated/assets/statemine/src/tests/teleport.rs
- parachains/integration-tests/emulated/assets/statemine/src/tests/transact.rs
- parachains/integration-tests/emulated/common/src/constants.rs
- parachains/integration-tests/emulated/common/src/lib.rs
- xcm/xcm-emulator/README.md
The actual tests are pretty much carbon copies aside from weight differences at the moment for reserve transfer assets.
(Also fixes some emulator typos - Event was meant to be Call.)
> add statemine emulator tests

- client/network/src/lib.rs
- parachains/integration-tests/e2e/assets/statemine/0_xcm/0_init.yml
- parachains/integration-tests/e2e/assets/statemine/0_xcm/1_dmp.yml
- parachains/integration-tests/e2e/assets/statemine/0_xcm/2_ump.yml
- parachains/integration-tests/e2e/assets/statemine/0_xcm/3_force_hrmp-open-channels.yml
- parachains/integration-tests/e2e/assets/statemine/0_xcm/4_hrmp.yml
- parachains/integration-tests/e2e/assets/statemine/config.toml
- parachains/integration-tests/e2e/assets/statemint/0_xcm/0_init.yml
- parachains/integration-tests/e2e/assets/statemint/0_xcm/1_dmp.yml
- parachains/integration-tests/e2e/assets/statemint/0_xcm/2_ump.yml
- parachains/integration-tests/e2e/assets/statemint/0_xcm/3_force_hrmp-open-channels.yml
- parachains/integration-tests/e2e/assets/statemint/0_xcm/4_hrmp.yml
- parachains/integration-tests/e2e/assets/statemint/config.toml
- parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/0_init.yml
- parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/1_teleport.yml
- parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/2_reserve.yml
- parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/0_join_alliance_fails.yml
- parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/1_init_alliance.yml
- parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/2_join_alliance_fails.yml
- parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/3_kick_member.yml
- parachains/integration-tests/e2e/collectives/collectives-polkadot/config.toml
- Update test to last parachains version `v9420`
- Revamp tests adding new threshold for weights.
First step for testing: https://github.com/paritytech/cumulus/pull/2285
> Update & revamp e2e tests

- Cargo.lock
- bridges/bin/runtime-common/src/mock.rs
- bridges/modules/messages/src/mock.rs
- bridges/modules/relayers/src/mock.rs
- pallets/collator-selection/src/mock.rs
- pallets/xcmp-queue/src/mock.rs
- parachain-template/runtime/src/lib.rs
- parachains/common/src/impls.rs
- parachains/runtimes/assets/statemine/src/lib.rs
- parachains/runtimes/assets/statemint/src/lib.rs
- parachains/runtimes/assets/westmint/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/penpal/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
- test/runtime/src/lib.rs
https://github.com/paritytech/substrate/pull/13869
> Companion for: Substrate#13869

- parachains/integration-tests/emulated/assets/statemint/src/tests/teleport.rs
Joe spotted a typo in a new emulator test. statemine/t is being renamed but that might take a while to land.
> Fix typo in test

- parachains/runtimes/glutton/glutton-kusama/src/lib.rs
`SignedExtra` was left misconfigured after adding `pallet_sudo`
> Add correct Sign Extensions to Glutton parachain

- Cargo.lock
- bridges/modules/grandpa/Cargo.toml
- bridges/primitives/header-chain/Cargo.toml
- bridges/primitives/header-chain/src/lib.rs
- bridges/primitives/messages/Cargo.toml
- bridges/primitives/messages/src/lib.rs
- bridges/primitives/runtime/Cargo.toml
- bridges/primitives/runtime/src/lib.rs
serde feature was NOT introduced into updated crates.
Required for https://github.com/paritytech/substrate/issues/13334
Companion for: paritytech/substrate#14261
> Serialize/Deserialize trait implemented in no-std for numerous types

- Cargo.lock
- client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
- pallets/parachain-system/src/lib.rs
This PR ensures that the CI step for docs will pass properly.
- use absolute crate paths for some  links
- downgrade links of `pub(super)` to simple mentions
Closes https://github.com/paritytech/cumulus/issues/2665
// @paritytech/subxt-team
> docs: Ensure the CI passes for docs

- Cargo.lock
This PR contains update of the polkadot deps to [the latest state](https://github.com/paritytech/polkadot/commit/0ede918bc1255fb46ccdd7b7b9f5c06b1e10b58a)
> Polkadot dependencies update runtimes

- .github/workflows/release-10_rc-automation.yml
- .github/workflows/release-30_create-draft.yml
GitHub is going to deprecate `save-state` and `set-output` commands. [More info](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
This PR adjusts GHA workflow to use new syntax.
Part of https://github.com/paritytech/ci_cd/issues/805
> CI: fix gha set-output command

- parachains/integration-tests/emulated/assets/asset-hub-kusama/src/lib.rs
- parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/mod.rs
- parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/reserve_transfer.rs
- parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/teleport.rs
- parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/transact.rs
- parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/lib.rs
- parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/mod.rs
- parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/reserve_transfer.rs
- parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/teleport.rs
- parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/transact.rs
- parachains/integration-tests/emulated/assets/asset-hub-westend/src/lib.rs
- parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/mod.rs
- parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/reserve_transfer.rs
- parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/teleport.rs
- parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/transact.rs
- parachains/integration-tests/emulated/collectives/collectives-polkadot/src/tests/fellowship.rs
- test/runtime/Cargo.toml
- xcm/xcm-emulator/src/lib.rs
The XCM messages are not passing between parachains right now, without manually calling `init` and `reset` before a test.
In the PR we preparing/opening the XCMP channels on a network initialization which happens once when `execute_with` invoke on any chain.
Calling just `reset` like in the examples [here](https://github.com/shaunxw/xcm-simulator/blob/d011e5ca62b93e8f688c2042c1f92cdbafc5d1d0/xcm-emulator/example/src/lib.rs#L195) does not help, since static params like PARA_IDS are not initialized. 
The PR also includes missing license headers for it tests.
> Xcm Emulator: prepare XCMP on init

- pallets/collator-selection/src/benchmarking.rs
Closes #2715 
See also:
https://github.com/paritytech/cumulus/issues/2715
> Fix max > T::MaxCandidates benchmark warning

- bridges/primitives/chain-bridge-hub-cumulus/src/lib.rs
Version gets bumped with https://github.com/paritytech/polkadot/pull/7341 breaking cumulus. This PR fixes this and should be merged before.
> Version independent import.

- Cargo.lock
- scripts/create_glutton_spec.sh
- test/service/benches/block_import_glutton.rs
- test/service/benches/block_production_glutton.rs
- test/service/benches/validate_block_glutton.rs
- test/service/src/bench_utils.rs
Companion for https://github.com/paritytech/substrate/pull/14338
Change:
- `Perbill` to `FixedU64`
- Rename `*_percent` to `*_ratio`
- Fix typos
> Co #14338: `pallet-glutton`: over-unity consumption

- Cargo.lock
(This includes the updates to relay chain migrations.)
> Bump polkadot version to released version

- Cargo.lock
Backporting polkadot bump to source https://github.com/paritytech/cumulus/pull/2742
> [backport] polkadot bump to source

- parachain-template/node/src/chain_spec.rs
- parachain-template/runtime/Cargo.toml
- parachain-template/runtime/src/lib.rs
To make the template node work out of the box.
Many new developers have complained about not being able to perform a runtime upgrade.
Unfortunately, there is no sudo or democracy available for this task.
Therefore, I have added the sudo in this PR.
> Add sudo to template node

- .github/pr-custom-review.yml
Fixed the problem that, if a member of two of the required teams reviews a Pr that belongs to `^parachains/runtimes/assets/(asset-hub-kusama|asset-hub-polkadot)/src/[^/]+\.rs$|^parachains/runtimes/bridge-hubs/(bridge-hub-kusama|bridge-hub-polkadot)/src/[^/]+\.rs$|^parachains/runtimes/collectives/collectives-polkadot/src/[^/]+\.rs$|^parachains/common/src/[^/]+\.rs$` it won't count as enough reviews.
By changing the `all_distinct` to `all` this will allow one member of both teams to fulfill the requirements for the PR
> fixed one member of two teams prs counting individually

- .github/workflows/srtool.yml
There are important fixes in subwasm v0.20.0. This PR ensures we install the latest version.
> Bump subwasm to latest

- parachains/runtimes/collectives/collectives-polkadot/src/fellowship/mod.rs
Closes #2777
Ranked Collective assumes that `PromoteOrigin` can provide a successful origin.
> Runtime: Root can promote on Polkadot Collectives

- .github/pr-custom-review.yml
- bridges/primitives/header-chain/tests/implementation_match.rs
- bridges/primitives/runtime/src/messages.rs
- parachain-template/node/src/command.rs
- parachains/runtimes/collectives/collectives-polkadot/src/fellowship/mod.rs
- polkadot-parachain/src/command.rs
This removes the requirement to pass the native executor dispatch.
> Companion for Substrate#14474

- parachains/runtimes/collectives/collectives-polkadot/src/fellowship/mod.rs
- parachains/runtimes/collectives/collectives-polkadot/src/impls.rs
This Pull Request addresses two issues encountered during the benchmark run:
1. Ranked collectives benchmarks:
An error occurs when the benchmarks attempt to promote a member above rank 9.
To resolve this, we have set the success value for the Root as the maximum value of u16.
We have employed a similar approach in the Polkadot runtime.
2. Salary pallet benchmarks:
In the benchmark environment, sending a message to a Parachain fails due to the absence of a channel between the Parachains.
To address this, we wrap the Pay implementation to open a channel with ensure_successful.
> Runtime: Success value and reachable location for Polkadot Collectives benchmarks

- xcm/xcm-emulator/src/lib.rs
I found out that the condition to process messages by a Parachain is incomplete.
We did not notice because of the coincidence that for all our tests, the destination Parachain that is supposed to receive/process the message, had been declared always before the other Parachains.
Example of failing case:
We send a message to `PenpalPolkadot`. The message will never reach its destination because `AssetHubPolkadot` will try to process it first as it is a message to the same `Network` `AssetHubPolkadot` and `PenpalPolkadot` live.
```rust
parachains = vec![
AssetHubPolkadot,
PenpalPolkadot,
],
```
Same test would pass just switching Parachains order declarations.
```rust
parachains = vec![
PenpalPolkadot,
AssetHubPolkadot,
],
```
Solution: filter also by `para_id` and not only by `Network`.
> Fix for `xcm-emulator` - Wrong Parachain processing message

- parachains/runtimes/assets/asset-hub-westend/src/lib.rs
Fixes compiler warning:
```
warning: type alias `Pool` is never used
--> parachains/runtimes/assets/asset-hub-westend/src/lib.rs:1169:9
|
1169 |             type Pool = pallet_assets::Pallet::<Runtime, PoolAssetsInstance>;
|                  ^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: type alias `Pool` is never used
--> parachains/runtimes/assets/asset-hub-westend/src/lib.rs:1307:9
|
1307 |             type Pool = pallet_assets::Pallet::<Runtime, PoolAssetsInstance>;
|                  ^^^^
```
> Fix Unused Variable for PoolAssets Benchmark

- parachains/integration-tests/emulated/assets/statemine/src/lib.rs
- parachains/integration-tests/emulated/assets/statemine/src/tests/mod.rs
- parachains/integration-tests/emulated/assets/statemine/src/tests/reserve_transfer.rs
- parachains/integration-tests/emulated/assets/statemine/src/tests/teleport.rs
- parachains/integration-tests/emulated/assets/statemine/src/tests/transact.rs
- parachains/integration-tests/emulated/assets/statemint/src/lib.rs
- parachains/integration-tests/emulated/assets/statemint/src/tests/mod.rs
- parachains/integration-tests/emulated/assets/statemint/src/tests/reserve_transfer.rs
- parachains/integration-tests/emulated/assets/statemint/src/tests/teleport.rs
- parachains/integration-tests/emulated/assets/statemint/src/tests/transact.rs
- parachains/integration-tests/emulated/collectives/collectives-polkadot/src/tests/fellowship.rs
- test/runtime/Cargo.toml
- xcm/xcm-emulator/src/lib.rs
Backporting `xcm-emulator` #2800 and #2711  fixes for a proper functioning in the release branch.
> Backport `xcm-emulator` fixes #2800 and #2711

- client/consensus/common/src/tests.rs
- client/network/src/lib.rs
- client/network/src/tests.rs
- client/relay-chain-inprocess-interface/src/lib.rs
- client/relay-chain-interface/src/lib.rs
- client/relay-chain-rpc-interface/src/lib.rs
This is particularly useful for fetching arbitrary relay chain headers within inherents.
> introduce a method for fetching relay chain header to `RelayChainInterface`

- Cargo.lock
- client/cli/Cargo.toml
- client/cli/src/lib.rs
- client/relay-chain-inprocess-interface/Cargo.toml
- parachain-template/node/src/command.rs
- polkadot-parachain/Cargo.toml
- polkadot-parachain/src/chain_spec/bridge_hubs.rs
- polkadot-parachain/src/command.rs
- polkadot-parachain/src/service.rs
- test/service/src/cli.rs
- test/service/src/main.rs
https://github.com/paritytech/substrate/pull/14511
`ExportGenesisStateCommand::run` now takes as a second argument something that implements `ExecutorProvider`. This parameter replaces the `state_version` by fetching this version internally from the given chain spec.
> Companion for Substrate#14511

- Cargo.lock
- client/collator/src/lib.rs
companion for https://github.com/paritytech/polkadot/pull/7405 , made against the feature branch
> CollationGenerationConfig closure is now optional

- client/relay-chain-rpc-interface/src/reconnecting_ws_client.rs
- pallets/parachain-system/src/lib.rs
- pallets/parachain-system/src/relay_state_snapshot.rs
- test/relay-sproof-builder/src/lib.rs
A temporary fix until all uses of relay_dispatch_queue_size are removed. Also renames several uses of RelayDispatchQueueSize to RelayDispatchQueueRemainingCapacity as appropriate.
> Better scoped fallback in read_messaging_state_snapshot() 

- pallets/collator-selection/src/lib.rs
Instead of loading always the entire `Vec` into the runtime to just decode the length, we can directly use `decode_len` to get this info.
> collator-selection: Optimize length decoding

- xcm/xcm-emulator/src/lib.rs
The processing of an XCM message should not trigger the network to process all the XCM channels, which happens if execute with `execute_with`.
The `ext_wrapper` will wrap the execution only with test externalities.
> Xcm-Emulator: use `ext_wrapper` to execute with externalities

- pallets/collator-selection/src/benchmarking.rs
Move from `frame_benchmarking::v1` to `frame_benchmarking::v2` in `pallet-collator-selection`.
> Use `benchmarking::v2` in collator selection pallet

- scripts/ci/gitlab/pipeline/benchmarks.yml
Quick fix of the typo in the PR name for `asset-hub-kusama`/`asset-hub-polkadot ` weights
> Fix PR name

- .github/workflows/release-10_rc-automation.yml
- .github/workflows/release-30_create-draft.yml
- .github/workflows/release-99_bot-announce.yml
WIP !
Similar to https://github.com/paritytech/polkadot/pull/7143
Move to the new matrix server and fix a few related things
cc @lazam @EgorPopelyaev @dartamendi-parity
> Change Matrix to new secrets and V2 server

- parachains/integration-tests/emulated/common/Cargo.toml
Was implicitly turned on before by a dep that has been recently removed by #2925 .
(without this if you go to `parachains/integration-tests/emulated/assets/asset-hub-westend` and run `cargo test` it will lead to compile errors.)
> Explicitly set `full-node` feature for emulated tests

- Cargo.lock
- parachains/runtimes/assets/asset-hub-kusama/tests/tests.rs
- parachains/runtimes/assets/asset-hub-polkadot/tests/tests.rs
- parachains/runtimes/assets/asset-hub-westend/tests/tests.rs
- primitives/utility/src/lib.rs
Companion to https://github.com/paritytech/polkadot/pull/7563
> Companion for Polkadot#7563

- parachains/chain-specs/bridge-hub-kusama.json
- parachains/chain-specs/collectives-polkadot.json
We are no longer using collators in the bootnode list; instead, we have replaced them with "connect" nodes. This change serves two purposes: first, it removes unnecessary load from collators, and secondly, it enables us to proceed with the planned decommission of collators nodes as outlined in [Referendum 84](https://polkadot.subsquare.io/referenda/referendum/84)
> Remove collators from bootnodes list

- .github/workflows/release-10_rc-automation.yml
Tiny fix to avoid failures while creating the release checklists due to wrong assignees
> fix failing gha because of the wrong assignee

- Cargo.lock
- client/cli/src/lib.rs
- client/relay-chain-inprocess-interface/src/lib.rs
- parachain-template/node/src/command.rs
- polkadot-parachain/src/command.rs
- test/service/src/cli.rs
- test/service/src/lib.rs
BEEFY is soon expected to run on all substrate-based chains.
Moved `--no-beefy` flag from polkadot specific cli to `sc-cli`.
Companion for https://github.com/paritytech/substrate/pull/14754
> companion for 14754: cli: move no-beefy flag to sc-cli

- pallets/xcmp-queue/src/lib.rs
This PR tries to simplify xcmp-queue, because there are coming:
https://github.com/paritytech/polkadot/pull/7005
https://github.com/paritytech/polkadot/pull/7585
https://github.com/paritytech/cumulus/pull/2433
https://github.com/paritytech/cumulus/pull/2342
So then we will be able to reuse lots of stuff.
> XcmpQueue simplify - `PriceForSiblingDelivery` replaced by `runtime::common::PriceForParachainDelivery`

- Cargo.lock
- client/cli/src/lib.rs
- client/relay-chain-inprocess-interface/src/lib.rs
- parachain-template/node/src/command.rs
- polkadot-parachain/src/command.rs
- test/service/src/cli.rs
- test/service/src/lib.rs
This reverts commit 9afe6a0cc4dc62760dd4dc7ecfca348989a12b81.
Based on https://github.com/paritytech/substrate/pull/14754#issuecomment-1677208626
companion for https://github.com/paritytech/polkadot/pull/7613
> Revert "companion for 14754: cli: move no-beefy flag to sc-cli (#2996)"

- parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
- parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
There's a bit of inconsistency in the diffs, most allow set-metadata, some don't. Set metadata is bounded by `StringLength` so it should be safe to call. This PR removes these inconsistencies to allow it everywhere.
> set-metadata is a safe call

- .dockerignore
- .github/workflows/release-50_docker-manual.yml
- .github/workflows/release-50_docker.yml
- docker/injected.Dockerfile
- docker/scripts/build-injected-image.sh
This should fix failing GHA which creates a docker image for the cumulus node.
> exclude polkadot-parachain.asc and .sha256 from .dockerignore

- scripts/ci/changelog/bin/changelog
This PR backports fix #2868 for the release notes generation from release-v1.0.0 branch to master
> [Backport] Fix release notes generation (#2868)

- pallets/parachain-system/src/lib.rs
This is very similar to the already existing `set_block_number`, but it also allows setting the `relay_parent_storage_root`.
We need this to be able to benchmark extrinsics that use StorageProofs in our project.
> Add set_current_relay_chain_state method for benchmarks

- scripts/benchmarks-ci.sh
RRemove the file name from the --output argument for the command that benchmarks the runtimes.
The benchmark CLI tool will automatically resolve the name if it's not provided. In cases where there are multiple instances of one pallet within a single runtime, the file name needs an instance name to avoid a collision. This is already supported by the CLI tool if the file name is omitted in the --output.
The current change to the script does not affect the name resolutions for the existing weights' files.
This change is required for this PR. - https://github.com/paritytech/cumulus/pull/2002
> benchmark script: remove file name for --output argument

- Cargo.lock
- parachain-template/node/Cargo.toml
- parachain-template/node/src/cli.rs
- parachain-template/node/src/command.rs
- polkadot-parachain/Cargo.toml
- polkadot-parachain/src/cli.rs
- polkadot-parachain/src/command.rs
- scripts/ci/gitlab/pipeline/test.yml
(preparation for the monorepo)
Changes;
- Warnings in the `cargo-check-try-runtime` CI should be treated as errors, since this is how it will be done in the monorepo.
- Remove try-runtime sub-command, analogous to https://github.com/paritytech/substrate/pull/14731
> Fix CI check and remove try-runtime command

- pallets/collator-selection/Cargo.toml
- pallets/collator-selection/src/mock.rs
- parachain-template/runtime/Cargo.toml
- parachain-template/runtime/src/lib.rs
- parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/hrmp_channels.rs
- parachains/integration-tests/emulated/assets/asset-hub-kusama/src/tests/teleport.rs
- parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/hrmp_channels.rs
- parachains/integration-tests/emulated/assets/asset-hub-polkadot/src/tests/teleport.rs
- parachains/integration-tests/emulated/assets/asset-hub-westend/src/tests/teleport.rs
- parachains/runtimes/assets/asset-hub-kusama/Cargo.toml
- parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
- parachains/runtimes/assets/asset-hub-polkadot/Cargo.toml
- parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
- parachains/runtimes/assets/asset-hub-westend/Cargo.toml
- parachains/runtimes/assets/asset-hub-westend/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/Cargo.toml
- parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
- parachains/runtimes/collectives/collectives-polkadot/Cargo.toml
- parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
- parachains/runtimes/contracts/contracts-rococo/Cargo.toml
- parachains/runtimes/contracts/contracts-rococo/src/lib.rs
- parachains/runtimes/testing/penpal/Cargo.toml
- parachains/runtimes/testing/penpal/src/lib.rs
- parachains/runtimes/testing/rococo-parachain/Cargo.toml
- parachains/runtimes/testing/rococo-parachain/src/lib.rs
(preparation for the monorepo)
Changes:
- When the `experimental` feature is enabled in the workspace, then `pallet-aura` expects an additional config item.
- Comment out some tests that fail when the `runtime-benchmarks` feature is enabled in the workspace. https://github.com/paritytech/cumulus/issues/3027 is linked in the code.
> Fix experimental `aura` config and comment tests

- Cargo.lock
(preparation for the monorepo)
To be refreshed on Friday before the sync-up. The hashes that we lock in here should be the ones that the scripts presents for importing @alvicsam. Substrate and Polkadot can already be in archived state for this to work.
Changes:
- Update to latest Substrate and Polkadot
Hash locks:
- Substrate: `033d4e86cc7eff0066cd376b9375f815761d653c`
- Polkadot: `52209dcfe546ff39cc031b92d64e787e7e8264d4`
- Cumulus: TBD
> Update to latest Substrate and Polkadot
