paritytech/cumulus

runtime/src/validate_block/implementation.rs
runtime/src/validate_block/mod.rs
runtime/src/validate_block/tests.rs

Pass parent hash to the validate_block function

---

.gitlab-ci.yml

runs all tests frozen and collects warnings

a simple CI for the start

---

Cargo.lock
Cargo.toml
network/Cargo.toml
network/src/lib.rs

implementation of BlockAnnounceValidator that checks for justifications in data

implementation of BlockAnnounceValidator

---

consensus/src/lib.rs

This fixes the `Safety violation:...` logging.
Fixes: https://github.com/paritytech/cumulus/issues/26

Don't finalize the same block multiple times

---

collator/src/lib.rs

See #35. I couldn't spot any other futures that were worth rewriting though.

`async`ify the big collator future

---

runtime/src/validate_block/implementation.rs

Closes: https://github.com/paritytech/cumulus/issues/38

Remove `unwrap_trie_error` and replace with `expect`

---

runtime/src/validate_block/implementation.rs

Fixes: https://github.com/paritytech/cumulus/issues/153

Harden storage against re-entry

---

runtime/src/validate_block/implementation.rs

Fixes: https://github.com/paritytech/cumulus/issues/155

Fix storage_append

---

collator/src/lib.rs
runtime/src/lib.rs
runtime/src/validate_block/implementation.rs
runtime/src/validate_block/tests.rs

Fixes: https://github.com/paritytech/cumulus/issues/151

Switch to `StorageProof`

---

Cargo.lock
test/parachain/src/service.rs

Graceful shutdown relay chain

---

Cargo.lock
runtime/Cargo.toml
runtime/src/validate_block/implementation.rs

Fixes: https://github.com/paritytech/cumulus/issues/194

Implement `storage::next_key`

---

rococo-parachains/src/command.rs

Fix `--parachain-id` CLI argument for `export-genesis-state` and don't
print genesis state without newline.
Fixes: https://github.com/paritytech/cumulus/issues/196

Fix `export-genesis-state`

---

Cargo.lock
parachain-upgrade/src/lib.rs

Update Polkadot reference and remove `ValidationFunction` to make usage

---

rococo-parachains/src/integration_test.rs
rococo-parachains/src/service.rs

It's not testing the right blocks :sweat: WIP
Related to #168

Test for not-validator mode

---

rococo-parachains/src/cli.rs
rococo-parachains/src/command.rs

Add --collator flag as alternative to --validator 

---

Cargo.lock
collator/Cargo.toml
collator/src/lib.rs
primitives/src/lib.rs
runtime/src/validate_block/implementation.rs

Integrate DMP into collation, take 2

---

Cargo.lock
rococo-parachains/src/service.rs
service/Cargo.toml
service/src/lib.rs

Fixes: https://github.com/paritytech/cumulus/issues/240

Bring back log prefixing

---

Cargo.lock
network/src/tests.rs

To fix the problems related to missing validator discovery runtime APIs.

Update Polkadot to the latest master

---

Cargo.lock
test/service/tests/integration.rs

Closes https://github.com/paritytech/cumulus/issues/229
Closes: https://github.com/paritytech/cumulus/issues/148

Fix syncing issues

---

collator/src/lib.rs

This is a base for the upcoming PR with HRMP integration, which will leverage the polkadot client to query HRMP channels contents.

Plumb polkadot client into the collator struct

---

Cargo.lock
collator/src/lib.rs
network/src/lib.rs
network/src/tests.rs
parachain-upgrade/src/lib.rs
rococo-parachains/runtime/src/lib.rs
runtime/src/validate_block/implementation.rs
service/src/lib.rs
test/runtime/src/lib.rs
test/service/src/lib.rs

**Description**
Fix #262, following substrate node template.

Upgdate to latest polkadot & substrate

---

Cargo.lock
collator/src/lib.rs
message-broker/src/lib.rs
network/src/lib.rs
network/src/tests.rs
primitives/src/lib.rs
rococo-parachains/src/service.rs
runtime/src/validate_block/implementation.rs
service/src/lib.rs
test/service/src/lib.rs

**Description**
Fix compilation issues with the latest Polkadot & substrate.

Update to latest polkadot & substrate

---

Cargo.lock
Cargo.toml
message-broker/src/lib.rs
primitives/src/lib.rs
rococo-parachains/runtime/Cargo.toml
rococo-parachains/runtime/src/lib.rs
xcm-handler/Cargo.toml
xcm-handler/src/lib.rs

This is a pallet which interfaces with the `cumulus-message-broker` to send and process XCM messages.

Add XCM Handler

---

README.md

- compile and start relay chain nodes
- compile and start parachain nodes
- register parachain on relay chain

add local setup to README

---

collator/src/lib.rs

This changes the collator to print an error if the block that we can not
find is the genesis block, instead of only logging this as a `debug`
message. This should help people when they have registered the wrong
genesis state on the relay chain.
CC @xlc

Print an error when we can not find the genesis block

---

rococo-parachains/runtime/src/lib.rs
xcm-handler/src/lib.rs

This also brings https://github.com/paritytech/cumulus/pull/309 to master

Fix HRMP Sibling Location

---

client/consensus/common/src/lib.rs

Followup to https://github.com/paritytech/cumulus/pull/329
Just fixes and clarifies a few little things from the docs.

Minor improvements to consensus docs

---

pallets/xcm-handler/src/lib.rs

`Success` and `Fail` events are defined but not deposited in handlers.

XCM handler: deposit XCM execution success and fail events.

---

pallets/xcm-handler/src/lib.rs
rococo-parachains/runtime/src/lib.rs

XCM handler: make send origin configurable.

---

Cargo.lock

```
cargo update -p sp-io
cargo update -p xcm
```

Bump Polkadot and Substrate deps

---

Cargo.lock
pallets/xcmp-queue/src/lib.rs
rococo-parachains/pallets/ping/src/lib.rs
rococo-parachains/runtime/src/lib.rs
rococo-parachains/shell-runtime/src/lib.rs

companion for https://github.com/paritytech/polkadot/pull/2940

Bump polkadot + fix parachain unnamed field

---

pallets/xcmp-queue/src/lib.rs

Fix condition in XCMP queue

---

Cargo.lock
client/service/src/lib.rs
pallets/dmp-queue/src/lib.rs
rococo-parachains/runtime/src/lib.rs

~CI can't pass until after paritytech/polkadot#2995 is in.~

Companion #2995: Dispatchable for teleporting assets

---

polkadot-parachains/src/command.rs

Before when loading a chain spec from a file it was always using the
rococo parachains runtime genesis config. This leaded to problems when
trying to convert a shell chain spec json file to a raw chain spec.

Fix chain spec handling

---

docker/docker-compose.yml
docker/scripts/inject_bootnodes.sh
docker/test-parachain-collator.dockerfile

Dunno how often these scripts are used, but this updates them.

rococo-collator -> polkadot-collator

---

Cargo.lock
pallets/collator-selection/src/mock.rs
polkadot-parachains/rococo-runtime/src/lib.rs
polkadot-parachains/statemine-runtime/src/lib.rs
polkadot-parachains/statemint-common/src/impls.rs
polkadot-parachains/statemint-runtime/src/lib.rs
polkadot-parachains/westmint-runtime/src/lib.rs
test/runtime/src/lib.rs

companion for https://github.com/paritytech/substrate/pull/7778
also updated librocksdb-sys so it compiles on Apple M1

update substrate & polkadot

---

polkadot-parachains/statemine-runtime/src/lib.rs
polkadot-parachains/statemint-runtime/src/lib.rs
polkadot-parachains/westmint-runtime/src/lib.rs

This PR: https://github.com/paritytech/cumulus/pull/495
Didn't rename everything

Fix Benchmark Rename

---

Cargo.lock
pallets/parachain-system/src/lib.rs

One breaking change:
- https://github.com/paritytech/substrate/pull/9209 cc @xlc

Update Polkadot and Substrate

---

pallets/parachain-system/src/lib.rs
pallets/parachain-system/src/tests.rs

Properly declare #[pallet::validate_unsigned] in ParachainSystem

---

client/cli/src/lib.rs
polkadot-parachains/src/command.rs

Rel https://github.com/paritytech/substrate/pull/8890

Add `rpc_http_threads`

---

.github/workflows/docs.yml

This ends what's started in https://github.com/paritytech/cumulus/pull/568
@bkchr, please merge.

docs: undebug docs build

---

polkadot-parachains/res/statemine.json
polkadot-parachains/res/statemine_genesis.json
polkadot-parachains/res/statemint.json
polkadot-parachains/res/tick.json
polkadot-parachains/res/track.json
polkadot-parachains/res/trick.json
polkadot-parachains/res/westmint.json
polkadot-parachains/res/westmint_genesis.json

necessary because of https://github.com/paritytech/substrate/pull/9491

remove lightSyncState field from chain specs

---

docker/injected.Dockerfile

cc https://github.com/paritytech/substrate/pull/9753 and https://github.com/paritytech/polkadot/pull/3828

dockerfiles: upgrade to ubuntu:20.04

---

Cargo.lock
polkadot-parachains/tests/purge_chain_works.rs

Fixes: https://github.com/paritytech/cumulus/issues/617

Fix purge-chain test

---

Cargo.lock
client/collator/src/lib.rs
pallets/dmp-queue/src/lib.rs
pallets/xcm/src/lib.rs
pallets/xcmp-queue/src/lib.rs
polkadot-parachains/pallets/ping/src/lib.rs
primitives/utility/src/lib.rs

Same procedure as not every day

---

Cargo.lock
parachain-template/runtime/src/lib.rs
polkadot-parachains/rococo/src/lib.rs
polkadot-parachains/statemine/src/lib.rs
polkadot-parachains/statemint/src/lib.rs
polkadot-parachains/westmint/src/lib.rs
test/runtime/src/lib.rs

companion for https://github.com/paritytech/substrate/pull/9834

update Substrate and Polkadot (to include new transaction priority)

---

polkadot-parachains/statemint/src/lib.rs

We want to launch Statemint in stages similar to Statemine.
We will thus limit the extrinsics for permissionless asset creation on launch and only enable them once we are ready.

disable permissionless asset creation for Statemint

---

pallets/dmp-queue/src/lib.rs
pallets/xcmp-queue/src/lib.rs
pallets/xcmp-queue/src/tests.rs

Backport #701 to the `polkadot-v0.9.12` branch.

Ensure a bad datastream cannot cause problems (#701)

---

CODEOWNERS

Sorry @chevdor . Didn't notice your mention :)

Add entry in `CODEOWNERS`

---

.github/workflows/draft_release.yml
scripts/changelog/bin/changelog

This PR fixes missing occurences of the rococo renaming.

Fix rococo naming

---

scripts/generate_genesis_value.sh
scripts/scale_encode_genesis/index.js

This PR is mostly adding additional checks, logs and doc which help me troubleshoot why the execution failed on my end initially.

Add checks, debug and doc

---

Cargo.lock
pallets/collator-selection/Cargo.toml
pallets/session-benchmarking/Cargo.toml
parachain-template/pallets/template/Cargo.toml
parachain-template/runtime/Cargo.toml
polkadot-parachains/statemine/Cargo.toml
polkadot-parachains/statemint/Cargo.toml
polkadot-parachains/westmint/Cargo.toml

polkadot companion: paritytech/polkadot#4387

Companion for #10324 - update frame-benchmarking/runtime-benchmarks

---

pallets/collator-selection/Cargo.toml
pallets/session-benchmarking/Cargo.toml
pallets/xcmp-queue/Cargo.toml
parachain-template/runtime/Cargo.toml
polkadot-parachains/Cargo.toml
polkadot-parachains/parachains-common/Cargo.toml
polkadot-parachains/rococo-parachain/Cargo.toml
polkadot-parachains/shell/Cargo.toml
polkadot-parachains/statemine/Cargo.toml
polkadot-parachains/statemint/Cargo.toml
polkadot-parachains/westmint/Cargo.toml
test/relay-sproof-builder/Cargo.toml

use double quotes instead of single quotes(For better matching when replacing batches)

Format cargo.toml

---

Cargo.lock
polkadot-parachains/rococo-parachain/src/lib.rs
polkadot-parachains/statemine/src/lib.rs
polkadot-parachains/statemint/src/lib.rs

https://github.com/paritytech/substrate/pull/10379
polkadot companion: paritytech/polkadot#4405

Companion for #10379 (EnsureOneOf)

---

.github/workflows/check-labels.yml
scripts/common/lib.sh
scripts/github/check_labels.sh

This PR adds the same `check_labels` check for PRs.

Add check_labels script and workflow

---

.github/workflows/release-02_create-draft.yml
scripts/changelog/bin/changelog
scripts/changelog/templates/changes_misc.md.tera
scripts/changelog/templates/docker_image.md.tera
scripts/changelog/templates/global_priority.md.tera
scripts/changelog/templates/high_priority.md.tera
scripts/changelog/templates/host_functions.md.tera
scripts/changelog/templates/pre_release.md.tera
scripts/changelog/templates/runtime.md.tera
scripts/changelog/templates/template.md.tera

Release notes fixes

---

polkadot-parachains/statemine/src/lib.rs
polkadot-parachains/statemint/src/lib.rs

Disable asset transfers on Statemint (against master branch)

---

Cargo.lock
parachain-template/node/src/command.rs
polkadot-parachains/src/command.rs

https://github.com/paritytech/substrate/pull/10440

Companion for #10440 (Add logger configuration hook)

---

Cargo.lock
client/service/src/lib.rs

https://github.com/paritytech/substrate/pull/10509

Substrate companion for fetching slot duration

---

Cargo.lock
client/network/src/tests.rs

Extracted from #872 not to block other PRs.

companion for polkadot#4542

---

pallets/parachain-system/src/tests.rs

fix the annotation on `receive_hrmp` test method, also add another dmp test case just like `receive_hrmp_after_pause`

minor dmq test

---

test/service/benches/transaction_throughput.rs

We need to give the accounts more coins!!

Fix transaction benchmark

---

Cargo.lock
test/service/src/lib.rs

https://github.com/paritytech/polkadot/pull/4639

Companion for #4639 (Remove sleep from tests )

---

Cargo.lock
pallets/parachain-system/src/tests.rs

Companion for https://github.com/paritytech/substrate/pull/10620

Companion for substrate#10620

---

Cargo.lock
polkadot-parachains/src/chain_spec.rs
polkadot-parachains/westmint/Cargo.toml
polkadot-parachains/westmint/src/lib.rs

It's really not necessary since everything can be done from Westend via XCM.

Remove Sudo from Westmint

---

polkadot-parachains/statemine/src/lib.rs

It needs to return the weight from on_runtimie_upgrade().

return weight from on_runtime_upgrade

---

polkadot-parachains/statemine/src/lib.rs
polkadot-parachains/statemint/src/lib.rs
polkadot-parachains/westmint/src/lib.rs

Merging https://github.com/paritytech/cumulus/pull/794 back to master.
(as part of https://github.com/paritytech/cumulus/issues/902 )

Configure Statemint and Statemine to Allow Teleports

---

.github/workflows/release-02_create-draft.yml

Pin the changelogerator version

---

Cargo.lock
polkadot-parachains/Cargo.toml

Bump the collator version https://github.com/paritytech/cumulus/pull/747 )
( part of https://github.com/paritytech/cumulus/issues/902 )

merge of Bump the collator version

---

Cargo.toml

See also https://github.com/paritytech/polkadot/pull/4778

Add production profile

---

pallets/xcmp-queue/src/lib.rs
pallets/xcmp-queue/src/tests.rs

This PR attempts to solve #801
polkadot address: 12zsKEDVcHpKEWb99iFt3xrTCQQXZMu477nJQsTBBrof5k2h

Add Setter for XCMP QueueConfigData

---

.github/workflows/release-02_create-draft.yml

See https://github.com/paritytech/cumulus/pull/959

ci: fix publish-runtimes for parachains containing - in name (v2) (backport of #959)

---

.github/workflows/release-02_create-draft.yml

https://github.com/paritytech/cumulus/pull/957 did not work. let's try that again :sweat_smile:

ci: fix publish-runtimes for parachains containing - in name (v2)

---

Cargo.lock
client/collator/Cargo.toml
client/collator/src/lib.rs
client/relay-chain-local/src/lib.rs

This enables us to also print the size of the compressed PoV.

Return compressed PoV from collation

---

polkadot-parachains/statemine/src/lib.rs
polkadot-parachains/westmint/src/lib.rs

Remove already run migrations. Record new migrations.
( part of https://github.com/paritytech/cumulus/issues/969 )

collective flip migration removed, uniques added (#965)

---

polkadot-parachains/canvas-kusama/src/lib.rs
polkadot-parachains/src/chain_spec.rs

We still accept the relay chain as sudo but for ease of development we add a sudo with a key known to the contracts team.

canvas: Add sudo

---

polkadot-parachains/canvas-kusama/src/contracts.rs
polkadot-parachains/canvas-kusama/src/lib.rs

* Move contracts config to own module
* Reduce usage of `parameter_types` where possible

canvas: More refactoring

---

Cargo.lock
client/network/Cargo.toml
client/pov-recovery/Cargo.toml
test/service/Cargo.toml

Companion for https://github.com/paritytech/substrate/pull/10894

Bump `tokio` to 1.17.0

---

parachain-template/node/Cargo.toml
polkadot-parachains/Cargo.toml
test/client/Cargo.toml
test/service/Cargo.toml

Replaces #1049 
Still unclear if all cargos that _should_ use this feature are actually implemented now. Please double check :pray:

Add wasmtime feature to all parachain clients

---

.github/workflows/release-10_docker-manual.yml

this'll allow us to manually kick off docker releases (i.e. in case the automated one failed)

ci: add manual docker release workflow

---

pallets/parachain-system/src/validate_block/implementation.rs

This reduces the amount of code a little bit.

Directly use the new `to_memory_db` function

---

pallets/collator-selection/src/lib.rs

One less collect, one less index and clippy suggestions.

collator-selection pallet tidy

---

Cargo.lock
polkadot-parachains/Cargo.toml
polkadot-parachains/rococo-parachain/src/lib.rs
polkadot-parachains/seedling/src/lib.rs
polkadot-parachains/statemine/src/lib.rs
polkadot-parachains/statemint/src/lib.rs
polkadot-parachains/westmint/src/lib.rs

Bump polkadot-collator and westmint/statemine/statemint versions.

bump versions in preparation for next release

---

pallets/xcmp-queue/src/lib.rs

No need to use indexes in a couple of places.
(Cleared up a couple of clippies while in the area.)

xcmp-queue / less indexing

---

Cargo.lock
polkadot-parachains/Cargo.toml
polkadot-parachains/rococo-parachain/src/lib.rs
polkadot-parachains/seedling/src/lib.rs
polkadot-parachains/statemine/src/lib.rs
polkadot-parachains/statemint/src/lib.rs
polkadot-parachains/westmint/src/lib.rs

* bump statemint runtimes versions
* Update lock file
* unifying runtime versions

bump version release

---

.github/workflows/release-10_docker-manual.yml
.github/workflows/release-10_docker.yml

Fix to publish to the right org

Fix target docker hub org

---

polkadot-parachains/canvas-kusama/src/lib.rs
polkadot-parachains/rococo-parachain/src/lib.rs
polkadot-parachains/seedling/src/lib.rs
polkadot-parachains/statemine/src/lib.rs
polkadot-parachains/statemint/src/lib.rs
polkadot-parachains/westmint/src/lib.rs

In preparation for the upcoming release bumping versions on master.

Bump version to v900

---

Cargo.lock
polkadot-parachains/Cargo.toml

In preparation for next release bumping collator version.

Bump collator version to 5.4

---

.github/pr-custom-review.yml

Sorry, the key was wrong in https://github.com/paritytech/cumulus/pull/1142

fix pr-custom-review.yml

---

Cargo.lock
parachain-template/node/src/command.rs
polkadot-parachains/src/command.rs

Companion for https://github.com/paritytech/substrate/pull/11198 and https://github.com/paritytech/polkadot/pull/5326

Co #11198: Expose `benchmark machine` command

---

polkadot-parachains/parachains-common/src/xcm_config.rs

missed one of the locations when doing https://github.com/paritytech/cumulus/pull/1169

warn not info

---

.github/workflows/pr-custom-review.yml

related to https://github.com/paritytech/pr-custom-review/issues/90

Skip pr-custom-review if pull request is in Draft

---

scripts/ci/changelog/templates/change.md.tera
scripts/ci/changelog/templates/high_priority.md.tera

Same than https://github.com/paritytech/polkadot/pull/5375

Fix priority thresholds

---

scripts/ci/changelog/templates/change.md.tera
scripts/ci/changelog/templates/high_priority.md.tera

Fix release notes prio backport (#1203)

---

scripts/benchmarks-ci.sh
scripts/benchmarks.sh

Updating bench scripts post https://github.com/paritytech/substrate/pull/11164

benchmark now takes a command

---

polkadot-parachains/parachains-common/src/xcm_config.rs

* warn not info
Co-authored-by: Keith Yeung <kungfukeith11@gmail.com>

warn not info (#1190)

---

Cargo.lock

Companion for https://github.com/paritytech/substrate/pull/11009
zeroize is downgraged in Cargo.lock.

Companion for substrate#11009

---

Cargo.lock
polkadot-parachains/statemine/src/weights/pallet_utility.rs
polkadot-parachains/statemint/src/weights/pallet_utility.rs
polkadot-parachains/westmint/src/weights/pallet_utility.rs

https://github.com/paritytech/substrate/pull/11148
https://github.com/paritytech/polkadot/pull/5452/files

Companion for Force Batch

---

.github/workflows/check-labels.yml
.github/workflows/docs.yml
.github/workflows/extrinsic-ordering-check-from-bin.yml
.github/workflows/quick-check.yml
.github/workflows/release-01_rc-automation.yml
.github/workflows/release-02_create-draft.yml
.github/workflows/release-10_docker-manual.yml
.github/workflows/release-10_docker.yml
.github/workflows/srtool.yml

- update of some GHA we use
- upgrade of subwasm to the latest 0.17.0

CI deps ugrade

---

Cargo.lock
parachain-template/node/src/command.rs
polkadot-parachains/src/command.rs

Polkadot: https://github.com/paritytech/polkadot/pull/5536

Companion for Polkadot #5536 (Remove Duplicate Traits)

---

.github/dependabot.yml

This PR add GitHub Actions support by `dependabot`

add GHA checks to dependabot

---

Cargo.lock
client/collator/src/lib.rs
parachain-template/node/src/rpc.rs
polkadot-parachain/src/rpc.rs

https://github.com/paritytech/polkadot/pull/5569

Companion for polkadot#5569

---

parachains/runtimes/assets/statemine/src/lib.rs
parachains/runtimes/assets/statemint/src/lib.rs
parachains/runtimes/assets/westmint/src/lib.rs
parachains/runtimes/contracts/contracts-rococo/src/lib.rs
parachains/runtimes/starters/seedling/src/lib.rs
parachains/runtimes/testing/rococo-parachain/src/lib.rs

Runtime version bump to 922

---

Cargo.lock
parachains/runtimes/assets/statemine/src/lib.rs
parachains/runtimes/assets/statemint/src/lib.rs
parachains/runtimes/assets/westmint/src/lib.rs
parachains/runtimes/contracts/contracts-rococo/src/lib.rs
parachains/runtimes/starters/seedling/src/lib.rs
parachains/runtimes/testing/rococo-parachain/src/lib.rs
polkadot-parachain/Cargo.toml

Node bump to v0.9.220

---

parachains/chain-specs/contracts-rococo.json
polkadot-parachain/src/chain_spec.rs

After renaming from canvas we also changed the bootnodes.

contracts: Update bootnodes

---

.gitlab-ci.yml
scripts/benchmarks-ci.sh
scripts/benchmarks.sh

Close but no cigar. Missed out the category.

Fixup benches after dir re-org

---

Cargo.lock

Update substrate after backport of [substrate #11593](https://github.com/paritytech/substrate/pull/11593)

Update substrate after #11593

---

.github/workflows/release-01_branch-check.yml
.gitlab-ci.yml
docker/polkadot-parachain-debug_unsigned_injected.Dockerfile
docker/test-parachain_injected.Dockerfile
scripts/benchmarks-ci.sh
scripts/benchmarks.sh
scripts/ci/changelog/templates/runtime.md.tera
scripts/ci/github/check-rel-br

This PR bring to the release branch a bunch of changes that are mainly CI related and fixes related to the new folder structure.
⚠️ This PR should not be squashed when merged.
@gilescope @gilescope @joepetrowski is there any non-yet-included PR you would like to add ?

Backports for v0.9.230

---

parachain-template/runtime/src/xcm_config.rs
parachains/common/src/xcm_config.rs
parachains/runtimes/assets/statemine/src/xcm_config.rs
parachains/runtimes/assets/statemint/src/xcm_config.rs
parachains/runtimes/assets/westmint/src/xcm_config.rs

https://github.com/paritytech/cumulus/pull/1318

Backport of 1318

---

.gitlab-ci.yml
scripts/benchmarks-ci.sh
scripts/benchmarks.sh

(Backport of #1300 to release branch)

fix benches backport

---

Cargo.lock
test/relay-validation-worker-provider/Cargo.toml
test/relay-validation-worker-provider/build.rs

close https://github.com/paritytech/pipeline-scripts/issues/45

Validation-worker: Add support for patches and rerun on Cargo.lock

---

.github/workflows/release-02_create-draft.yml

Backport of PR #1292 already in master.

Fix client workflow (#1292 backport to release branch)

---

parachain-template/runtime/src/xcm_config.rs
parachains/common/src/xcm_config.rs
parachains/runtimes/assets/statemine/src/xcm_config.rs
parachains/runtimes/assets/statemint/src/xcm_config.rs
parachains/runtimes/assets/westmint/src/xcm_config.rs

* recognise no reserves
* adjust should_execute
* docs and pass should_execute
* typo

Backport of 1318 to collator release branch (#1348)

---

.gitlab-ci.yml

* Fix `release-parachains-v*` pipelines
* Formatting

Backport to runtime release branch of Fix `release-parachains-v*` pipelines (#1355)

---

parachains/runtimes/assets/statemine/src/constants.rs
parachains/runtimes/assets/statemine/src/lib.rs
parachains/runtimes/assets/statemint/src/constants.rs
parachains/runtimes/assets/statemint/src/lib.rs
parachains/runtimes/assets/westmint/src/constants.rs
parachains/runtimes/assets/westmint/src/lib.rs
parachains/runtimes/contracts/contracts-rococo/src/constants.rs

Backport #1332

---

client/relay-chain-inprocess-interface/src/lib.rs

Should fix https://github.com/paritytech/substrate/issues/11604

Disable beefy for inprocess relay chain node

---

parachains/runtimes/assets/statemine/src/lib.rs
parachains/runtimes/assets/statemint/src/lib.rs
parachains/runtimes/assets/westmint/src/lib.rs

(In line with the collectives common good chain)

NonTransfer should be a superset of collator selection

---

Cargo.lock
client/collator/Cargo.toml
client/consensus/aura/Cargo.toml
client/consensus/common/Cargo.toml
client/consensus/relay-chain/Cargo.toml
client/network/Cargo.toml
client/pov-recovery/Cargo.toml
polkadot-parachain/Cargo.toml
primitives/timestamp/Cargo.toml
test/service/Cargo.toml

Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Remove futures compat feature

---

Cargo.toml

Adding collectives polkadot runtime package to cargo workspace members

Collectives polkadot runtime to cargo workspace members

---

parachain-template/node/src/command.rs

Just some leftovers from #1303

Rename help string `parachain-collator` -> `parachain-template-node`

---

README.md

Updating readme file with installation instructions referring to Substrate installation doc.

README: installation instructions

---

scripts/ci/changelog/templates/changes.md.tera

Remove left over runtime sections for client builds

---

.github/workflows/release-10_docker-manual.yml
.github/workflows/release-10_docker.yml

This part being missing changes to the previous fix.

Second part of the Docker CI fix

---

.gitlab-ci.yml
scripts/benchmarks-ci.sh

PR adds a job that publishes benchmark results to S3
Part of https://github.com/paritytech/ci_cd/issues/468

[ci] Send bench results to S3

---

.github/workflows/release-99_bot-announce.yml

This add a room to the list of Matrix notifications.
See related https://github.com/paritytech/polkadot/pull/5764

Add new room to the matrix notifications

---

Cargo.lock
client/cli/src/lib.rs
parachain-template/node/src/command.rs
polkadot-parachain/src/command.rs
test/service/src/cli.rs

Companion PR for https://github.com/paritytech/substrate/pull/11786
Bumped Substrate & Polkadot version in Cargo.lock to fix build

Companion for substrate#11786

---

Cargo.lock
pallets/parachain-system/Cargo.toml
pallets/parachain-system/src/validate_block/implementation.rs
test/runtime/src/lib.rs

This is a companion PR for https://github.com/paritytech/substrate/pull/11523

Companion for substrate#11523

---

.gitlab-ci.yml

Fix https://github.com/paritytech/opstooling/issues/111
Example of PR: https://github.com/substrate-developer-hub/substrate-node-template/pull/363
Pipeline-script: https://github.com/paritytech/pipeline-scripts/pull/71

Integrate auto-updating parachain template on developer-hub

---

.github/workflows/release-02_create-draft.yml
scripts/ci/changelog/templates/runtime.md.tera

better branch name than before. Continuation of https://github.com/paritytech/cumulus/pull/1471

Fixes for relnotes

---

.gitlab-ci.yml

* Integrate auto-updating parachain template on developer-hub
* Update .gitlab-ci.yml
Co-authored-by: Alexander Samusev <41779041+alvicsam@users.noreply.github.com>
Co-authored-by: Alexander Samusev <41779041+alvicsam@users.noreply.github.com>

Integrate auto-updating parachain template on developer-hub (#1479)

---

.github/ISSUE_TEMPLATE/release-client.md
.github/ISSUE_TEMPLATE/release-runtime.md

It seems that the `-` break the templates

Fix templates

---

.github/workflows/release-01_branch-check.yml
scripts/ci/github/check-rel-br

Same than https://github.com/paritytech/polkadot/pull/5751

Same than https://github.com/paritytech/polkadot/pull/5751

---

.github/ISSUE_TEMPLATE/release-client.md
.github/ISSUE_TEMPLATE/release-runtime.md
.github/workflows/release-01_branch-check.yml
scripts/ci/github/check-rel-br

See also:
- #1508
- #1510
- #1506

Backport of few fixes

---

Cargo.lock
test/service/src/lib.rs

Related (companion) to [this Substrate PR](https://github.com/paritytech/substrate/pull/11934)

Renaming CLI prunning and keep-blocks flags

---

.gitlab-ci.yml

Release branch cherry pick of https://github.com/paritytech/cumulus/pull/1518

[Fix] Benches in release branch

---

Cargo.lock
polkadot-parachain/Cargo.toml
polkadot-parachain/tests/common.rs
polkadot-parachain/tests/polkadot_argument_parsing.rs
polkadot-parachain/tests/polkadot_mdns_issue.rs
polkadot-parachain/tests/purge_chain_works.rs
polkadot-parachain/tests/running_the_node_and_interrupt.rs

Fixes https://github.com/paritytech/cumulus/issues/1520
NOTE: This needs to be further refined as we can't wait for blocks on collators, hence for now it's just a timeout after getting the WS url. We shall see how to improve this in later iterations.

[Fix] flaky node tests

---

.github/ISSUE_TEMPLATE/blank.md

This is to help having an option to create a new issue without having to search for the mini link down the list.

Add new blank issue template

---

Cargo.lock
parachains/runtimes/collectives/collectives-polkadot/src/impls.rs

https://github.com/paritytech/substrate/pull/12179

Companion for substrate#12179

---

parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs

Addendum to #1629 : We don't want westmint chain halting either ideally.

Westmint don't panic.

---

parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs

Cherry pick https://github.com/paritytech/cumulus/pull/1641 to runtime release branch.

Cherry pick teleport xcm fix to runtime release branch

---

parachains/runtimes/assets/statemine/src/lib.rs
parachains/runtimes/assets/statemint/src/lib.rs
parachains/runtimes/assets/westmint/src/lib.rs

original PR https://github.com/paritytech/cumulus/pull/1647

Cherry pick transaction_version from master

---

parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs

Deposit set at pre-benchmark value.

[Fix] Deposit weight hardcoded to pre-bench value

---

parachains/runtimes/assets/statemine/src/weights/xcm/mod.rs
parachains/runtimes/assets/statemint/src/weights/xcm/mod.rs
parachains/runtimes/assets/westmint/src/weights/xcm/mod.rs

cherrypick https://github.com/paritytech/cumulus/pull/1651 to node rel branch

cherrypick deposit asset xcm fix to node rel branch

---

parachains/runtimes/collectives/collectives-polkadot/src/weights/frame_system.rs
parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_alliance.rs
parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_balances.rs
parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_collator_selection.rs
parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_multisig.rs
parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_proxy.rs
parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_session.rs
parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_timestamp.rs
parachains/runtimes/collectives/collectives-polkadot/src/weights/pallet_utility.rs

This PR is generated automatically by CI.

[benchmarks] Update weights for collectives

---

Cargo.lock

PR to update the substrate dependencies

Update substrate dependencies

---

scripts/benchmarks-ci.sh

* xcm benchmarks use a custom template.

backport: set xcm weights template (#1643)

---

Cargo.lock
polkadot-parachain/Cargo.toml

backport: Bump crate versions

---

Cargo.lock
parachains/runtimes/contracts/contracts-rococo/src/contracts.rs

https://github.com/paritytech/substrate/pull/12421

Companion for contracts WeightV2

---

.github/workflows/docs.yml

This PR adds protoc for the rustdoc workflow

Add protoc

---

.github/workflows/fmt-check.yml

Agreed with @chevdor that master should have this check as well

[ci] check fmt on master

---

.github/workflows/docs.yml

`sudo`...
Follow-up of #1730 
Test done: https://github.com/chevdor/cumulus/actions/runs/3190745397/jobs/5206254436

Fix protoc install

---

.github/pr-custom-review.yml
.gitlab-ci.yml
scripts/ci/gitlab/pipeline/benchmarks.yml
scripts/ci/gitlab/pipeline/build.yml
scripts/ci/gitlab/pipeline/integration_tests.yml
scripts/ci/gitlab/pipeline/publish.yml
scripts/ci/gitlab/pipeline/test.yml
scripts/ci/gitlab/pipeline/zombienet.yml

PR splits `.gitlab-ci.yml` into several files. 
@pepoviola please check `zombienet.yml` and approve if you agree with it. I removed repeatable parts and used templating.
close https://github.com/paritytech/ci_cd/issues/622

[ci] Split .gitlab-ci.yml

---

Cargo.lock
parachains/runtimes/contracts/contracts-rococo/src/lib.rs

https://github.com/paritytech/substrate/pull/12469

contracts: Companion for offchain indeterminism

---

Cargo.lock
parachains/runtimes/assets/statemine/src/lib.rs
parachains/runtimes/assets/statemint/src/lib.rs
parachains/runtimes/assets/westmint/src/lib.rs
parachains/runtimes/collectives/collectives-polkadot/src/lib.rs
parachains/runtimes/contracts/contracts-rococo/src/lib.rs

https://github.com/paritytech/substrate/pull/12457
https://github.com/paritytech/polkadot/pull/6172

Companion for #12457 (Bounded Multisig)

---

Cargo.lock

https://github.com/paritytech/substrate/pull/12280

Companion for update `wasm-opt`

---

Cargo.lock

This pr updates source release branch with the latest substrate and polkadot deps

update substrate and polkadot deps

---

Cargo.lock

`cargo update -p sp-io -p polkadot-runtime`

Cargo.lock updated

---

scripts/ci/gitlab/pipeline/publish.yml

Current buildah image is broken. Using the previous one
cc https://github.com/paritytech/ci_cd/issues/671

[ci] fix buildah

---

parachains/chain-specs/statemine.json

This bootnode is going to be decommissioned.

Remove 1 Parity Statemine bootnode that will be decommisioned

---

.github/ISSUE_TEMPLATE/release-runtime.md

Release checklist extended with one more task - Push Collective runtime upgrade

add collective runtime upgrade to the checklist

---

.gitlab-ci.yml

The PR changes runners to the new ones

[ci] new ci runners

---

parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs

Implements https://github.com/paritytech/parity-bridges-common/issues/1162 for Rococo <> Wococo

Add BridgeRejectObsoleteHeadersAndMessages to bridge hubs

---

parachains/integration-tests/statemint/xcm/4_hrmp.yml

Backport of #1954 to master
(as functionallity is rolled out)

add test onto statemint as well as statemine now (#1954)

---

parachains/integration-tests/collectives/0_xcm/0_init.yml
parachains/integration-tests/collectives/0_xcm/1_teleport.yml
parachains/integration-tests/collectives/0_xcm/2_reserve.yml
parachains/integration-tests/collectives/1_alliance/0_join_alliance_fails.yml
parachains/integration-tests/collectives/1_alliance/1_init_alliance.yml
parachains/integration-tests/collectives/1_alliance/2_join_alliance_fails.yml
parachains/integration-tests/collectives/1_alliance/3_kick_member.yml
parachains/integration-tests/collectives/config.toml

Integration tests for Polkadot Collectives.

Collectives chain integration tests

---

Cargo.lock

This PR should fix dependencies duplications in the Cargo.lock file

fix deps duplications in Cargo.lock

---

parachains/integration-tests/collectives/0_xcm/1_teleport.yml
parachains/integration-tests/collectives/1_alliance/1_init_alliance.yml
parachains/integration-tests/collectives/1_alliance/3_kick_member.yml

In this PR:
- flaky test replaced by stable
- assertion for pre and post teleport balances
- update weights

Collectives parachain integration tests update

---

scripts/ci/gitlab/pipeline/publish.yml

`update-parachain-template` will be moved to Polkadot's pipeline in https://github.com/paritytech/polkadot/pull/6541
related to https://github.com/paritytech/release-engineering/issues/142

Remove update-parachain-template

---

Cargo.lock

This PR contains update of the dependencies to polkadot, due to new transaction_versions in polkadot release branch

update polkadot dependencies

---

parachains/runtimes/contracts/contracts-rococo/src/contracts.rs

This is a companion PR for https://github.com/paritytech/substrate/pull/12993

Companion for substrate#12993

---

.github/workflows/check-D-labels.yml
.github/workflows/check-labels.yml

cc https://github.com/paritytech/ci_cd/issues/587

[ci] Update check-labels and fix check

---

parachains/chain-specs/collectives-polkadot.json
parachains/chain-specs/statemine.json
parachains/chain-specs/statemint.json
parachains/chain-specs/westmint.json

Hello,
We would like to add our bootnodes to the following system parachains:
Westmint, Statemine, Statemint, Collectives (polkadot)
Thanks

Add stake.plus bootnodes to system parachains

---

scripts/ci/changelog/bin/changelog

This PR fixes the changelog generation failing in the `Release - Create Draft` GHA

fix failing changelog generation

---

Cargo.lock

This PR backport deps update from runtimes release branch

[backport] Update polkadot dependencies (#2208) to node

---

Cargo.lock

This PR backport deps update from runtimes release branch

[backport] Update polkadot dependencies (#2208) to source

---

scripts/ci/changelog/Gemfile
scripts/ci/changelog/Gemfile.lock
scripts/ci/changelog/bin/changelog
scripts/ci/changelog/templates/change.md.tera
scripts/ci/changelog/templates/changes.md.tera
scripts/ci/changelog/templates/changes_api.md.tera
scripts/ci/changelog/templates/changes_client.md.tera
scripts/ci/changelog/templates/changes_misc.md.tera
scripts/ci/changelog/templates/debug.md.tera
scripts/ci/changelog/templates/high_priority.md.tera
scripts/ci/changelog/templates/host_functions.md.tera
scripts/ci/changelog/templates/migrations-db.md.tera
scripts/ci/changelog/templates/migrations-runtime.md.tera

* More fixes
* Add API section and various fixes

Fix templates (Backport of #2204)

---

parachains/chain-specs/bridge-hub-kusama.json
parachains/chain-specs/collectives-polkadot.json
parachains/chain-specs/collectives-westend.json
parachains/chain-specs/statemine.json
parachains/chain-specs/statemint.json
parachains/chain-specs/westmint.json

We would like to add our bootnodes to the following parachains:
Westend
- Westmint
- Collectives
Kusama
- Statemine
- BridgeHub
Polkadot
- Statemint
- Collectives
Thanks

Add metaspan.io parachain boot nodes

---

.gitattributes
.gitlab-ci.yml
scripts/ci/gitlab/pipeline/benchmarks.yml
scripts/ci/gitlab/pipeline/build.yml
scripts/ci/gitlab/pipeline/publish.yml
scripts/ci/gitlab/pipeline/test.yml
scripts/ci/gitlab/pipeline/zombienet.yml
scripts/ci/gitlab/prettier.sh

cf https://github.com/paritytech/substrate/pull/13441

Automatically format ci pipeline specs with prettier

---

parachains/chain-specs/bridge-hub-kusama.json
parachains/chain-specs/collectives-polkadot.json
parachains/chain-specs/collectives-westend.json
parachains/chain-specs/statemine.json
parachains/chain-specs/statemint.json
parachains/chain-specs/westmint.json

Add Helikon boot nodes for Westmint, Statemine, Statemint, Collectives Polkadot, Collectives Westend and Bridge Hub Kusama.
Westmint:
```
polkadot-parachain --chain westmint --reserved-only --reserved-nodes "/dns/boot-node.helikon.io/tcp/10200/p2p/12D3KooWMRY8wb7rMT81LLuivvsy6ahUxKHQgYJw4zm1hC1uYLxb"
```
Statemine:
```
polkadot-parachain --chain statemine --reserved-only --reserved-nodes "/dns/boot-node.helikon.io/tcp/10210/p2p/12D3KooWFXRQce3aMgZMn5SxvHtYH4PsR63TZLf8LrnBsEVTyzdr"
```
Statemint:
```
polkadot-parachain --chain statemint --reserved-only --reserved-nodes "/dns/boot-node.helikon.io/tcp/10220/p2p/12D3KooW9uybhguhDjVJc3U3kgZC3i8rWmAnSpbnJkmuR7C6ZsRW"
```
Collectives Polkadot:
```
polkadot-parachain --chain collectives-polkadot --reserved-only --reserved-nodes …
```

Add Helikon boot nodes

---

Cargo.lock
parachains/runtimes/assets/statemine/src/weights/pallet_assets.rs
parachains/runtimes/assets/statemint/src/weights/pallet_assets.rs
parachains/runtimes/assets/westmint/src/weights/pallet_assets.rs

Companion for #13486

---

Cargo.lock
client/relay-chain-minimal-node/src/collator_overseer.rs

This is a companion for https://github.com/paritytech/polkadot/pull/6727

Don't pass `leaves()` to `Overseer::builder()`

---

Cargo.lock
parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs

Mainly to bring polkadot#6787 in

Update polkadot 0.9.38

---

parachains/chain-specs/bridge-hub-kusama.json
parachains/chain-specs/collectives-polkadot.json
parachains/chain-specs/collectives-westend.json
parachains/chain-specs/statemine.json
parachains/chain-specs/statemint.json
parachains/chain-specs/westmint.json

Hi,
these are the amforcs bootnodes for statemint, collectives-polkadot, statemine, bridge-hub-kusama, westmint, collectives-westend.
To verify:
Statemint:
```
polkadot-parachain --chain statemint --reserved-only --reserved-nodes "/dns/statemint.bootnode.amforc.com/tcp/30341/p2p/12D3KooWByohP9FXn7ao8syS167qJsbFdpa7fY2Y24xbKtt3r7Ls"
```
collectives polkadot:
```
polkadot-parachain --chain collectives-polkadot --reserved-only --reserved-nodes "/dns/collectives-polkadot.bootnode.amforc.com/tcp/30335/p2p/12D3KooWQeAjDnGkrPe5vtpfnB6ydZfWyMxyrXLkBFmA6o4k9aiU"
```
statemine:
```
polkadot-parachain --chain statemine --reserved-only --reserved-nodes "/dns/statemine.bootnode.amforc.com/tcp/30336/p2p/12D3KooWHmSyrBWsc6fdpq8HtCFWasmLVLYGKWA2a78m4xAHKyBq"
```
bridge-hub-kusama:
```
polkadot-parachain …
```

add amforc bootnodes

---

Cargo.lock
parachains/runtimes/assets/statemine/tests/tests.rs
parachains/runtimes/assets/statemint/tests/tests.rs
parachains/runtimes/assets/westmint/tests/tests.rs

This syncs the latest changes in Substrate and fixes the import path of the runtime api.

Fix runtime api import path

---

pallets/dmp-queue/src/lib.rs

This PR backports #2343 from master to the release 9382 branch

[Backport] dmp-queue: Store messages if already processed more than the maximum 

---

.gitlab-ci.yml

Includes several fixes, including for this error (https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/2550651).
Thanks!
cc @skunert

bump `zombienet` to v1.3.40

---

.gitlab-ci.yml

cf https://github.com/paritytech/ci_cd/issues/757

Bump ci-linux image for rust 1.68

---

Cargo.lock
client/relay-chain-inprocess-interface/Cargo.toml

Companion for: https://github.com/paritytech/polkadot/pull/6916

Revert #2304

---

Cargo.lock

This PR backports deps updates from the runtimes release branch to the source release branch

[backport] deps update from runtimes to source

---

.gitlab-ci.yml
scripts/ci/gitlab/pipeline/build.yml
scripts/ci/gitlab/pipeline/test.yml

for https://github.com/paritytech/ci_cd/issues/767

use stable rust toolchain in ci

---

Cargo.lock
client/relay-chain-minimal-node/src/collator_overseer.rs
client/service/src/lib.rs

Followup for https://github.com/paritytech/polkadot/pull/7131
Also mark the consensus task as blocking, since it is importing and finalizing which are performing blocking operations.

Skip av-store in collator overseer

---

Cargo.lock
client/network/src/lib.rs

This PR contains backport of the polkadot dependencies update from release runtimes branch

[Backport] Update polkadot dependencies (#2509) to source branch

---

Cargo.lock
client/network/src/lib.rs

This PR backports polkadot dependencies update from release runtimes branch

[Backport ]Update polkadot dependencies (#2509) to client release branch

---

.gitlab-ci.yml
zombienet/tests/register-para.js

Bump version to support new substrate cli args version.
Thanks!!

bump zombienet version

---

parachains/runtimes/assets/statemine/src/xcm_config.rs
parachains/runtimes/assets/westmint/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs

This is needed to change the invulnerable collators on test and production networks.

Add `set_invulnerables` to `SafeCallFilter`

---

client/network/src/lib.rs
parachains/runtimes/assets/statemine/src/xcm_config.rs
parachains/runtimes/assets/westmint/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs

This PR backports #2537 from master to the runtimes release branch

[Backport] add set_invulnerables to SafeCallFilter (#2537) to release runtimes branch

---

Cargo.lock
parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs

This PR backports #2550 and substrate dependencies update to the runtimes release branch

[Backport] #2550 and substrate deps update to runtimes release

---

Cargo.lock
parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs

This PR backports #2550 and substrate dependencies update  to the runtimes release branch

[Backport] #2550 and substrate deps update to source release

---

Cargo.lock
parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs

This PR backports #2550 and substrate dependencies update  to the client release branch

[Backport] #2550 and substrate deps update to client release

---

Cargo.lock
polkadot-parachain/Cargo.toml
polkadot-parachain/src/command.rs

companion for https://github.com/paritytech/substrate/pull/14134

remove sp-serializer

---

parachains/chain-specs/bridge-hub-kusama.json
parachains/chain-specs/bridge-hub-polkadot.json
parachains/chain-specs/bridge-hub-westend.json
parachains/chain-specs/collectives-polkadot.json
parachains/chain-specs/collectives-westend.json
parachains/chain-specs/statemine.json
parachains/chain-specs/statemint.json
parachains/chain-specs/westmint.json

I have tested all the endpoints using
`./polkadot-parachain --chain <chain> --reserved-only --reserved-nodes <endpoint>`

Added Dwellir bootnodes.

---

test/service/src/lib.rs

Companion PR for substrate https://github.com/paritytech/substrate/pull/13800

companion for substrate#13800

---

parachains/chain-specs/bridge-hub-kusama.json
parachains/chain-specs/bridge-hub-polkadot.json
parachains/chain-specs/bridge-hub-westend.json
parachains/chain-specs/collectives-polkadot.json
parachains/chain-specs/collectives-westend.json
parachains/chain-specs/statemine.json
parachains/chain-specs/statemint.json
parachains/chain-specs/westmint.json

Closes: https://github.com/paritytech/cumulus/issues/2609

Chainspecs: Fix bootnode address

---

Cargo.lock
client/network/src/lib.rs
xcm/xcm-emulator/src/lib.rs

Slight changes to emulator needed to cope with latest master.

Update substrate/polkadot + needed changes to compile

---

Cargo.lock
parachains/runtimes/collectives/collectives-polkadot/src/fellowship/migration.rs

Companion for: https://github.com/paritytech/substrate/pull/13993
Polkadot companion: https://github.com/paritytech/polkadot/pull/7146

Try-runtime proper return types

---

Cargo.lock

Just bumping substrate pulled in to latest.

bump substrate version

---

Cargo.lock
polkadot-parachain/src/chain_spec/glutton.rs
scripts/create_glutton_spec.sh

Script to generate Glutton Parachains `chain_spec.json` files based on `para_id`, `sudo` and `pallet_glutton` storage config values.

Glutton script chain spec generator

---

Cargo.lock

Companion for: https://github.com/paritytech/substrate/pull/14237
// @paritytech/subxt-team

Companion for #14237: Use latest sp-crates

---

Cargo.lock
client/network/src/lib.rs

This PR updates polkadot deps to the latest state

Update polkadot dependencies in runtimes release branch

---

Cargo.lock

This PR contains update of the polkadot deps to the latest state

Polkadot dependencies update runtimes

---

Cargo.lock

This PR contains update of the polkadot deps to [the latest state](https://github.com/paritytech/polkadot/commit/0ede918bc1255fb46ccdd7b7b9f5c06b1e10b58a)

Update polkadot dependencies source

---

Cargo.lock

This PR contains update of the polkadot deps to [the latest state](https://github.com/paritytech/polkadot/commit/0ede918bc1255fb46ccdd7b7b9f5c06b1e10b58a)

Update polkadot dependencies client

---

Cargo.lock
pallets/xcmp-queue/src/mock.rs
parachain-template/runtime/src/xcm_config.rs
parachains/runtimes/assets/asset-hub-kusama/src/lib.rs
parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs
parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
parachains/runtimes/assets/asset-hub-westend/src/lib.rs
parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/lib.rs
parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/lib.rs
parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs
parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs
parachains/runtimes/glutton/glutton-kusama/src/xcm_config.rs
parachains/runtimes/starters/shell/src/xcm_config.rs
parachains/runtimes/testing/penpal/src/xcm_config.rs
parachains/runtimes/testing/rococo-parachain/src/lib.rs

companion for https://github.com/paritytech/polkadot/pull/7245

companion for xcm alias origin

---

Cargo.lock
parachains/integration-tests/e2e/assets/asset-hub-kusama/0_xcm/2_ump.yml
parachains/integration-tests/e2e/assets/asset-hub-polkadot/0_xcm/2_ump.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/1_teleport.yml

Update tests: ump.ExecutedUpward now called messageQueue.Processed

Update integration tests following event rename

---

Cargo.lock
client/relay-chain-minimal-node/src/blockchain_rpc_client.rs
client/relay-chain-rpc-interface/src/rpc_client.rs
parachains/integration-tests/emulated/common/src/lib.rs

Companion for https://github.com/paritytech/polkadot/pull/7341

---

pallets/collator-selection/src/lib.rs

companion but also can be merged ahead https://github.com/paritytech/substrate/pull/14375
import vec from sp_std instead of hidden re-export in inherent

Minor refactor on imports

---

Cargo.lock

Because of https://github.com/paritytech/cumulus/issues/2727

Bump substrate

---

Cargo.lock

Backporting polkadot bump to source https://github.com/paritytech/cumulus/pull/2742

[backport] polkadot bump to client

---

.github/workflows/release-20_extrinsic-ordering-check-from-bin.yml
.github/workflows/release-30_create-draft.yml
scripts/ci/changelog/bin/changelog

Renaming of the Asset Hubs

---

parachains/pallets/ping/Cargo.toml

Fixes: https://github.com/paritytech/cumulus/issues/2704

add try-runtime to ping pallet

---

.github/pr-custom-review.yml

Reverts paritytech/cumulus#2770
why: because it was wrong fix, the proper one here https://github.com/paritytech/pr-custom-review/pull/115

Revert "fixed one member of two teams prs counting individually"

---

parachains/integration-tests/e2e/assets/asset-hub-kusama/0_xcm/0_init.yml
parachains/integration-tests/e2e/assets/asset-hub-kusama/0_xcm/1_dmp.yml
parachains/integration-tests/e2e/assets/asset-hub-kusama/0_xcm/2_ump.yml
parachains/integration-tests/e2e/assets/asset-hub-kusama/0_xcm/4_hrmp.yml
parachains/integration-tests/e2e/assets/asset-hub-polkadot/0_xcm/0_init.yml
parachains/integration-tests/e2e/assets/asset-hub-polkadot/0_xcm/1_dmp.yml
parachains/integration-tests/e2e/assets/asset-hub-polkadot/0_xcm/2_ump.yml
parachains/integration-tests/e2e/assets/asset-hub-polkadot/0_xcm/4_hrmp.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/0_init.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/1_teleport.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/2_reserve.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/1_init_alliance.yml

(also made some of the results to be in one line
so they are similar to the others)

Update integration tests: Tuple changed to struct

---

Cargo.lock

Relates to: https://github.com/paritytech/cumulus/pull/2846
Relates to: https://github.com/paritytech/cumulus/issues/2806

Bump substrate (because of failing asset-hub-westend benchmarks)

---

scripts/ci/changelog/bin/changelog

This PR fixes failing release note publishing.

Fix release notes generation source

---

scripts/ci/changelog/bin/changelog

This PR fixes failing release note publishing.

Fix release notes generation runtimes

---

scripts/ci/changelog/bin/changelog

This PR fixes failing release note publishing.

Fix release notes generation node

---

Cargo.lock

This PR updates substrate dependencies to the latest state

Update substrate dependencies node

---

Cargo.lock
client/relay-chain-inprocess-interface/Cargo.toml
client/relay-chain-minimal-node/Cargo.toml
client/service/Cargo.toml
parachain-template/node/Cargo.toml

This feature allows nodes to connect on protocol version 2.

propagate network-protocol-staging feature from parachain-template

---

parachains/integration-tests/e2e/collectives/README.md
parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/0_init.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/1_teleport.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/0_xcm/3_hrmp-open-channels.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/1_init_alliance.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/1_alliance/3_kick_member.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/2_opengov/0_assethub.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/3_fellowship/0_init.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/3_fellowship/1_whitelist_call.yml
parachains/integration-tests/e2e/collectives/collectives-polkadot/3_fellowship/2_assethub.yml

e2e tests for Polkadot Public Referenda and Fellowship

e2e tests for Gov2

---

templates/xcm-bench-template.hbs

update weight file template

---

parachains/common/src/xcm_config.rs
parachains/runtimes/assets/asset-hub-kusama/src/xcm_config.rs
parachains/runtimes/assets/asset-hub-polkadot/src/xcm_config.rs
parachains/runtimes/assets/asset-hub-westend/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-kusama/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-polkadot/src/xcm_config.rs
parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs
parachains/runtimes/collectives/collectives-polkadot/src/xcm_config.rs
parachains/runtimes/contracts/contracts-rococo/src/xcm_config.rs

Addresses https://github.com/paritytech/cumulus/pull/2842#discussion_r1291732439

Combine `NativeAsset` into `ConcreteNativeAssetFromSystem`

---

Cargo.lock
client/relay-chain-inprocess-interface/src/lib.rs
test/service/src/lib.rs

https://github.com/paritytech/polkadot/pull/7617

Companion for Polkadot#7617

---

parachains/chain-specs/bridge-hub-polkadot.json
parachains/chain-specs/bridge-hub-westend.json

Bridge Hub Polkadot:
```
polkadot-parachain --chain=bridge-hub-polkadot --tmp --relay-chain-rpc-url wss://rpc.ibp.network/polkadot  --reserved-only --reserved-nodes /dns/boot-node.helikon.io/tcp/8220/p2p/12D3KooWC38TZJA8ZBXZgAYVrceoJ56jNNLJPdpk3ojeFkTAwZVp
polkadot-parachain --chain=bridge-hub-polkadot --tmp --relay-chain-rpc-url wss://rpc.ibp.network/polkadot  --reserved-only --reserved-nodes /dns/boot-node.helikon.io/tcp/8222/wss/p2p/12D3KooWC38TZJA8ZBXZgAYVrceoJ56jNNLJPdpk3ojeFkTAwZVp
```
Bridge Hub Westend:
```
/polkadot-parachain --chain=bridge-hub-westend --tmp --relay-chain-rpc-url wss://rpc.ibp.network/westend  --reserved-only --reserved-nodes /dns/boot-node.helikon.io/tcp/9220/p2p/12D3KooWK3K1Mu5Jjg96Lt9DUzg84KsWnZo44V4KB7mvhGqi6xnp
/polkadot-parachain --chain=bridge-hub-westend …
```

Add Helikon boot nodes for Bridge Hub Polkadot and Bridge Hub Westend.

---

.dockerignore
.github/workflows/release-50_docker-manual.yml
.github/workflows/release-50_docker.yml
docker/injected.Dockerfile
docker/scripts/build-injected-image.sh

This PR backports #3013 from release-v1.0.0 back to master

[Backport] Fix for the docker image creation from release branch (#3013)

---

Cargo.lock

https://github.com/paritytech/substrate/pull/14776

Companion for substrate#14776
